import { getMemPos, readMem16, readMem8, writeMem16, writeMem8 } from '../common/memory';
import { get8, set16 } from '../common/utils';
import { executeMain } from './execute';
import { executeBit } from './execute-bit';
import { executeMisc } from './execute-misc';
import { bitFC, bitFH, bitFPV, bitFS, bitFZ } from './flags';
import { call } from './op/op-call';
import { DI, EI, HALT } from './op/op-control';
import { EX_AF_AF, EX_DE_HL, EX_sp_HL, EXX } from './op/op-exchange';
import { IN_A_n, OUT_n_A } from './op/op-io';
import { DJNZ_e, JR_e } from './op/op-jump';
import { _ADD_HL_SS, _DEC_SS, _INC_SS } from './op/op-math-16bit';
import { _DEC_Rhl, _INC_Rhl, add, cp, logic, sub } from './op/op-math-8bit';
import { CCF, CPL, DAA, SCF } from './op/op-math-etc';
import { RLA, RLCA, RRA, RRCA } from './op/op-shift';
import { posA, posB, posC, posD, posE, posF, posH, posL, posSPh, posSPl } from './positions';
import { HLMode } from './types';
import { _getAF, _getD, _getE, _getH, _getHL, _getL, _setD, _setE, _setH, _setHL, _setL, getA, getB, getBC, getC, getDE, getF, getFC, getHalt, getSP, incPC, next16, next8, pop16, push16, refresh, setA, setB, setBC, setC, setDE, setHLMode, setPC, setSP } from './utils';

let ops: (() => void)[];

export function _executeMain() {
  refresh();
  if (getHalt()) return;
  const op = next8();
  ops[op]();
}

export function _initExecuteMain() {
  ops = [
    /* 00 NOP        */ () => { },
    /* 01 LD BC,nn   */ () => setBC(next16()),
    /* 02 LD (BC),A  */ () => writeMem8(getBC(), getA()),
    /* 03 INC BC     */ () => _INC_SS(posB, posC),
    /* 04 INC B      */ () => _INC_Rhl(posB),
    /* 05 DEC B      */ () => _DEC_Rhl(posB),
    /* 06 LD B,n     */ () => setB(next8()),
    /* 07 RLCA       */ RLCA,
    /* 08 EX AF,AF'  */ EX_AF_AF,
    /* 09 ADD HL,BC  */ () => _ADD_HL_SS(getBC()),
    /* 0A LD A,(BC)  */ () => setA(readMem8(getBC())),
    /* 0B DEC BC     */ () => _DEC_SS(posB, posC),
    /* 0C INC C      */ () => _INC_Rhl(posC),
    /* 0D DEC C      */ () => _DEC_Rhl(posC),
    /* 0E LD C,n     */ () => setC(next8()),
    /* 0F RRCA       */ RRCA,

    /* 10 DJNZ e     */ DJNZ_e,
    /* 11 LD DE,nn   */ () => setDE(next16()),
    /* 12 LD (DE),A  */ () => writeMem8(getDE(), getA()),
    /* 13 INC DE     */ () => _INC_SS(posD, posE),
    /* 14 INC D      */ () => _INC_Rhl(posD),
    /* 15 DEC D      */ () => _DEC_Rhl(posD),
    /* 16 LD D,n     */ () => _setD(next8()),
    /* 17 RLA        */ RLA,
    /* 18 JR e       */ JR_e,
    /* 19 ADD HL,DE  */ () => _ADD_HL_SS(getDE()),
    /* 1A LD A,(DE)  */ () => setA(readMem8(getDE())),
    /* 1B DEC DE     */ () => _DEC_SS(posD, posE),
    /* 1C INC E      */ () => _INC_Rhl(posE),
    /* 1D DEC E      */ () => _DEC_Rhl(posE),
    /* 1E LD E,n     */ () => _setE(next8()),
    /* 1F RRA        */ RRA,

    /* 20 JR NZ,e    */ () => get8(posF) & bitFZ ? incPC(1) : JR_e(),
    /* 21 LD HL,nn   */ () => _setHL(next16()),
    /* 22 LD (nn),HL */ () => writeMem16(next16(), _getHL()),
    /* 23 INC HL     */ () => _INC_SS(posH, posL),
    /* 24 INC H      */ () => _INC_Rhl(posH),
    /* 25 DEC H      */ () => _DEC_Rhl(posH),
    /* 26 LD H,n     */ () => _setH(next8()),
    /* 27 DAA        */ DAA,
    /* 28 JR Z,e     */ () => get8(posF) & bitFZ ? JR_e() : incPC(1),
    /* 29 ADD HL,HL  */ () => _ADD_HL_SS(_getHL()),
    /* 2A LD HL,(nn) */ () => _setHL(readMem16(next16())),
    /* 2B DEC HL     */ () => _DEC_SS(posH, posL),
    /* 2C INC L      */ () => _INC_Rhl(posL),
    /* 2D DEC L      */ () => _DEC_Rhl(posL),
    /* 2E LD L,n     */ () => _setL(next8()),
    /* 2F CPL        */ CPL,

    /* 30 JR NC,e    */ () => get8(posF) & bitFC ? incPC(1) : JR_e(),
    /* 31 LD SP,nn   */ () => setSP(next16()),
    /* 32 LD (nn),A  */ () => writeMem8(next16(), getA()),
    /* 33 INC SP     */ () => _INC_SS(posSPh, posSPl),
    /* 34 INC (HL)   */ () => _INC_Rhl(getMemPos(_getHL())),
    /* 35 DEC (HL)   */ () => _DEC_Rhl(getMemPos(_getHL())),
    /* 36 LD (HL),n  */ () => writeMem8(_getHL(), next8()),
    /* 37 SCF        */ SCF,
    /* 38 JR C,e     */ () => get8(posF) & bitFC ? JR_e() : incPC(1),
    /* 39 ADD HL,SP  */ () => _ADD_HL_SS(getSP()),
    /* 3A LD A,(nn)  */ () => setA(readMem8(next16())),
    /* 3B DEC SP     */ () => _DEC_SS(posSPh, posSPl),
    /* 3C INC A      */ () => _INC_Rhl(posA),
    /* 3D DEC A      */ () => _DEC_Rhl(posA),
    /* 3E LD A,n     */ () => setA(next8()),
    /* 3F CCF        */ CCF,

    /* 40 LD B,B     */ () => { },
    /* 41 LD B,C     */ () => setB(getC()),
    /* 42 LD B,D     */ () => setB(_getD()),
    /* 43 LD B,E     */ () => setB(_getE()),
    /* 44 LD B,H     */ () => setB(_getH()),
    /* 45 LD B,L     */ () => setB(_getL()),
    /* 46 LD B,(HL)  */ () => setB(readMem8(_getHL())),
    /* 47 LD B,A     */ () => setB(getA()),
    /* 48 LD C,B     */ () => setC(getB()),
    /* 49 LD C,C     */ () => { },
    /* 4A LD C,D     */ () => setC(_getD()),
    /* 4B LD C,E     */ () => setC(_getE()),
    /* 4C LD C,H     */ () => setC(_getH()),
    /* 4D LD C,L     */ () => setC(_getL()),
    /* 4E LD C,(HL)  */ () => setC(readMem8(_getHL())),
    /* 4F LD C,A     */ () => setC(getA()),

    /* 50 LD D,B     */ () => _setD(getB()),
    /* 51 LD D,C     */ () => _setD(getC()),
    /* 52 LD D,D     */ () => { },
    /* 53 LD D,E     */ () => _setD(_getE()),
    /* 54 LD D,H     */ () => _setD(_getH()),
    /* 55 LD D,L     */ () => _setD(_getL()),
    /* 56 LD D,(HL)  */ () => _setD(readMem8(_getHL())),
    /* 57 LD D,A     */ () => _setD(getA()),
    /* 58 LD E,B     */ () => _setE(getB()),
    /* 59 LD E,C     */ () => _setE(getC()),
    /* 5A LD E,D     */ () => _setE(_getD()),
    /* 5B LD E,E     */ () => { },
    /* 5C LD E,H     */ () => _setE(_getH()),
    /* 5D LD E,L     */ () => _setE(_getL()),
    /* 5E LD E,(HL)  */ () => _setE(readMem8(_getHL())),
    /* 5F LD E,A     */ () => _setE(getA()),

    /* 60 LD H,B     */ () => _setH(getB()),
    /* 61 LD H,C     */ () => _setH(getC()),
    /* 62 LD H,D     */ () => _setH(_getD()),
    /* 63 LD H,E     */ () => _setH(_getE()),
    /* 64 LD H,H     */ () => { },
    /* 65 LD H,L     */ () => _setH(_getL()),
    /* 66 LD H,(HL)  */ () => _setH(readMem8(_getHL())),
    /* 67 LD H,A     */ () => _setH(getA()),
    /* 68 LD L,B     */ () => _setL(getB()),
    /* 69 LD L,C     */ () => _setL(getC()),
    /* 6A LD L,D     */ () => _setL(_getD()),
    /* 6B LD L,E     */ () => _setL(_getE()),
    /* 6C LD L,H     */ () => _setL(_getH()),
    /* 6D LD L,L     */ () => { },
    /* 6E LD L,(HL)  */ () => _setL(readMem8(_getHL())),
    /* 6F LD L,A     */ () => _setL(getA()),

    /* 70 LD (HL),B  */ () => writeMem8(_getHL(), getB()),
    /* 71 LD (HL),C  */ () => writeMem8(_getHL(), getC()),
    /* 72 LD (HL),D  */ () => writeMem8(_getHL(), _getD()),
    /* 73 LD (HL),E  */ () => writeMem8(_getHL(), _getE()),
    /* 74 LD (HL),H  */ () => writeMem8(_getHL(), _getH()),
    /* 75 LD (HL),L  */ () => writeMem8(_getHL(), _getL()),
    /* 76 HALT       */ HALT,
    /* 77 LD (HL),A  */ () => writeMem8(_getHL(), getA()),
    /* 78 LD A,B     */ () => setA(getB()),
    /* 79 LD A,C     */ () => setA(getC()),
    /* 7A LD A,D     */ () => setA(_getD()),
    /* 7B LD A,E     */ () => setA(_getE()),
    /* 7C LD A,H     */ () => setA(_getH()),
    /* 7D LD A,L     */ () => setA(_getL()),
    /* 7E LD A,(HL)  */ () => setA(readMem8(_getHL())),
    /* 7F LD A,A     */ () => { },

    /* 80 ADD A,B    */ () => add(getB(), 0),
    /* 81 ADD A,C    */ () => add(getC(), 0),
    /* 82 ADD A,D    */ () => add(_getD(), 0),
    /* 83 ADD A,E    */ () => add(_getE(), 0),
    /* 84 ADD A,H    */ () => add(_getH(), 0),
    /* 85 ADD A,L    */ () => add(_getL(), 0),
    /* 86 ADD A,(HL) */ () => add(readMem8(_getHL()), 0),
    /* 87 ADD A,A    */ () => add(getA(), 0),
    /* 88 ADC A,B    */ () => add(getB(), getFC()),
    /* 89 ADC A,C    */ () => add(getC(), getFC()),
    /* 8A ADC A,D    */ () => add(_getD(), getFC()),
    /* 8B ADC A,E    */ () => add(_getE(), getFC()),
    /* 8C ADC A,H    */ () => add(_getH(), getFC()),
    /* 8D ADC A,L    */ () => add(_getL(), getFC()),
    /* 8E ADC A,(HL) */ () => add(readMem8(_getHL()), getFC()),
    /* 8F ADC A,A    */ () => add(getA(), getFC()),

    /* 90 SUB B      */ () => sub(getB(), 0),
    /* 91 SUB C      */ () => sub(getC(), 0),
    /* 92 SUB D      */ () => sub(_getD(), 0),
    /* 93 SUB E      */ () => sub(_getE(), 0),
    /* 94 SUB H      */ () => sub(_getH(), 0),
    /* 95 SUB L      */ () => sub(_getL(), 0),
    /* 96 SUB (HL)   */ () => sub(readMem8(_getHL()), 0),
    /* 97 SUB A      */ () => sub(getA(), 0),
    /* 98 SBC A,B    */ () => sub(getB(), getFC()),
    /* 99 SBC A,C    */ () => sub(getC(), getFC()),
    /* 9A SBC A,D    */ () => sub(_getD(), getFC()),
    /* 9B SBC A,E    */ () => sub(_getE(), getFC()),
    /* 9C SBC A,H    */ () => sub(_getH(), getFC()),
    /* 9D SBC A,L    */ () => sub(_getL(), getFC()),
    /* 9E SBC A,(HL) */ () => sub(readMem8(_getHL()), getFC()),
    /* 9F SBC A,A    */ () => sub(getA(), getFC()),

    /* A0 AND B      */ () => logic(getA() & getB(), bitFH),
    /* A1 AND C      */ () => logic(getA() & getC(), bitFH),
    /* A2 AND D      */ () => logic(getA() & _getD(), bitFH),
    /* A3 AND E      */ () => logic(getA() & _getE(), bitFH),
    /* A4 AND H      */ () => logic(getA() & _getH(), bitFH),
    /* A5 AND L      */ () => logic(getA() & _getL(), bitFH),
    /* A6 AND (HL)   */ () => logic(getA() & readMem8(_getHL()), bitFH),
    /* A7 AND A      */ () => logic(getA(), bitFH),
    /* A8 XOR B      */ () => logic(getA() ^ getB(), 0),
    /* A9 XOR C      */ () => logic(getA() ^ getC(), 0),
    /* AA XOR D      */ () => logic(getA() ^ _getD(), 0),
    /* AB XOR E      */ () => logic(getA() ^ _getE(), 0),
    /* AC XOR H      */ () => logic(getA() ^ _getH(), 0),
    /* AD XOR L      */ () => logic(getA() ^ _getL(), 0),
    /* AE XOR (HL)   */ () => logic(getA() ^ readMem8(_getHL()), 0),
    /* AF XOR A      */ () => logic(0, 0),

    /* B0 OR B       */ () => logic(getA() | getB(), 0),
    /* B1 OR C       */ () => logic(getA() | getC(), 0),
    /* B2 OR D       */ () => logic(getA() | _getD(), 0),
    /* B3 OR E       */ () => logic(getA() | _getE(), 0),
    /* B4 OR H       */ () => logic(getA() | _getH(), 0),
    /* B5 OR L       */ () => logic(getA() | _getL(), 0),
    /* B6 OR (HL)    */ () => logic(getA() | readMem8(_getHL()), 0),
    /* B7 OR A       */ () => logic(getA(), 0),
    /* B8 CP B       */ () => cp(getB()),
    /* B9 CP C       */ () => cp(getC()),
    /* BA CP D       */ () => cp(_getD()),
    /* BB CP E       */ () => cp(_getE()),
    /* BC CP H       */ () => cp(_getH()),
    /* BD CP L       */ () => cp(_getL()),
    /* BE CP (HL)    */ () => cp(readMem8(_getHL())),
    /* BF CP A       */ () => cp(getA()),

    /* C0 RET NZ     */ () => getF() & bitFZ ? {} : setPC(pop16()),
    /* C1 POP BC     */ () => set16(posB, posC, pop16()),
    /* C2 JP NZ,nn   */ () => getF() & bitFZ ? incPC(2) : setPC(next16()),
    /* C3 JP nn      */ () => setPC(next16()),
    /* C4 CALL NZ,nn */ () => getF() & bitFZ ? incPC(2) : call(next16()),
    /* C5 PUSH BC    */ () => push16(getBC()),
    /* C6 ADD A,n    */ () => add(next8(), 0),
    /* C7 CALL 00h   */ () => call(0x00),
    /* C8 RET Z      */ () => getF() & bitFZ ? setPC(pop16()) : {},
    /* C9 RET        */ () => setPC(pop16()),
    /* CA JP Z,nn    */ () => getF() & bitFZ ? setPC(next16()) : incPC(2),
    /* CB ---------- */ executeBit,
    /* CC CALL Z,nn  */ () => getF() & bitFZ ? call(next16()) : incPC(2),
    /* CD CALL nn    */ () => call(next16()),
    /* CE ADC A,n    */ () => add(next8(), getFC()),
    /* CF CALL 08h   */ () => call(0x08),

    /* D0 RET NC     */ () => getFC() ? {} : setPC(pop16()),
    /* D1 POP DE     */ () => set16(posD, posE, pop16()),
    /* D2 JP NC,nn   */ () => getFC() ? incPC(2) : setPC(next16()),
    /* D3 OUT (n),A  */ OUT_n_A,
    /* D4 CALL NC,nn */ () => getFC() ? incPC(2) : call(next16()),
    /* D5 PUSH DE    */ () => push16(getDE()),
    /* D6 SUB A,n    */ () => sub(next8(), 0),
    /* D7 CALL 10h   */ () => call(0x10),
    /* D8 RET C      */ () => getFC() ? setPC(pop16()) : {},
    /* D9 EXX        */ EXX,
    /* DA JP C,nn    */ () => getFC() ? setPC(next16()) : incPC(2),
    /* DB IN A,(n)   */ IN_A_n,
    /* DC CALL C,nn  */ () => getFC() ? call(next16()) : incPC(2),
    /* DD ---------- */ () => { setHLMode(HLMode.IX); executeMain(); setHLMode(HLMode.HL); },
    /* DE SBC A,n    */ () => sub(next8(), getFC()),
    /* DF CALL 18h   */ () => call(0x18),

    /* E0 RET PO     */ () => getF() & bitFPV ? {} : setPC(pop16()),
    /* E1 POP HL     */ () => set16(posH, posL, pop16()),
    /* E2 JP PO,nn   */ () => getF() & bitFPV ? incPC(2) : setPC(next16()),
    /* E3 EX (SP),HL */ EX_sp_HL,
    /* E4 CALL PO,nn */ () => getF() & bitFPV ? incPC(2) : call(next16()),
    /* E5 PUSH HL    */ () => push16(_getHL()),
    /* E6 AND n      */ () => logic(getA() & next8(), bitFH),
    /* E7 CALL 20h   */ () => call(0x20),
    /* E8 RET PE     */ () => getF() & bitFPV ? setPC(pop16()) : {},
    /* E9 JP (HL)    */ () => setPC(_getHL()),
    /* EA JP PE,nn   */ () => getF() & bitFPV ? setPC(next16()) : incPC(2),
    /* EB EX DE,HL   */ EX_DE_HL,
    /* EC CALL PE,nn */ () => getF() & bitFPV ? call(next16()) : incPC(2),
    /* ED ---------- */ executeMisc,
    /* EE XOR n      */ () => logic(getA() ^ next8(), 0),
    /* EF CALL 28h   */ () => call(0x28),

    /* F0 RET P      */ () => getF() & bitFS ? {} : setPC(pop16()),
    /* F1 POP AF     */ () => set16(posA, posF, pop16()),
    /* F2 JP P,nn    */ () => getF() & bitFS ? incPC(2) : setPC(next16()),
    /* F3 DI         */ DI,
    /* F4 CALL P,nn  */ () => getF() & bitFS ? incPC(2) : call(next16()),
    /* F5 PUSH AF    */ () => push16(_getAF()),
    /* F6 OR n       */ () => logic(getA() | next8(), 0),
    /* F7 RST 30h    */ () => call(0x30),
    /* F8 RET M      */ () => getF() & bitFS ? setPC(pop16()) : {},
    /* F9 LD SP,HL   */ () => setSP(_getHL()),
    /* FA JP M,nn    */ () => getF() & bitFS ? setPC(next16()) : incPC(2),
    /* FB EI         */ EI,
    /* FC CALL M,nn  */ () => getF() & bitFS ? call(next16()) : incPC(2),
    /* FD ---------- */ () => { setHLMode(HLMode.IY); executeMain(); setHLMode(HLMode.HL); },
    /* FE CP n       */ () => cp(next8()),
    /* FF CALL 38h   */ () => call(0x38),
  ];
}
