import { get, set } from '../common/utils';
import { executeBit } from './execute-bit';
import { executeBitXYd } from './execute-bit-xyd';
import { executeMisc } from './execute-misc';
import { fc, FH, fo, fs, fz, HLT, hlt, IFF1, IFF2, setHLT, setIFF1, setIFF2 } from './flags';
import { EX_AF_AF, EX_DE_HL, EX_sp_HL, EXX } from './op/op-exchange';
import { IN_A_n, OUT_n_A } from './op/op-io';
import { DJNZ_e, JR_e } from './op/op-jump';
import { ld16, ld16Next, ldReg16 } from './op/op-load-16bit';
import { addHLXY, decReg16, incReg16 } from './op/op-math-16bit';
import { add, cp, dec, decReg, inc, incReg, logic, sub } from './op/op-math-8bit';
import { CCF, CPL, DAA, SCF } from './op/op-math-etc';
import { RLA, RLCA, RRA, RRCA } from './op/op-shift';
import { call88, callNext16, pop16, popAF, push16, pushAF } from './op/op-stack';
import { A, B, BC, C, D, DE, E, getReg16, H, HL, HLXY, HXY, IX, IY, L, LXY, PC, PCh, PCl, regs, setEIDelay, setHLXY, SP, SPh, SPl } from './registers';
import { addPC, getHLXYd, next, next16, nop, refresh, setPCNext16 } from './utils';

export function executeMain() {
  refresh();
  if (hlt) return;
  const op = next();
  opsMain[op]();
}

const opsMain = [
  /* 00 NOP        */ nop,
  /* 01 LD BC,nn   */ () => ld16Next(BC),
  /* 02 LD (BC),A  */ () => set(getReg16(BC), regs[A]),
  /* 03 INC BC     */ () => incReg16(BC),
  /* 04 INC B      */ () => incReg(B),
  /* 05 DEC B      */ () => decReg(B),
  /* 06 LD B,n     */ () => regs[B] = next(),
  /* 07 RLCA       */ RLCA,
  /* 08 EX AF,AF'  */ EX_AF_AF,
  /* 09 ADD HL,BC  */ () => addHLXY(BC),
  /* 0A LD A,(BC)  */ () => regs[A] = get(getReg16(BC)),
  /* 0B DEC BC     */ () => decReg16(BC),
  /* 0C INC C      */ () => incReg(C),
  /* 0D DEC C      */ () => decReg(C),
  /* 0E LD C,n     */ () => regs[C] = next(),
  /* 0F RRCA       */ RRCA,

  /* 10 DJNZ e     */ DJNZ_e,
  /* 11 LD DE,nn   */ () => ld16Next(DE),
  /* 12 LD (DE),A  */ () => set(getReg16(DE), regs[A]),
  /* 13 INC DE     */ () => incReg16(DE),
  /* 14 INC D      */ () => incReg(D),
  /* 15 DEC D      */ () => decReg(D),
  /* 16 LD D,n     */ () => regs[D] = next(),
  /* 17 RLA        */ RLA,
  /* 18 JR e       */ JR_e,
  /* 19 ADD HL,DE  */ () => addHLXY(DE),
  /* 1A LD A,(DE)  */ () => regs[A] = get(getReg16(DE)),
  /* 1B DEC DE     */ () => decReg16(DE),
  /* 1C INC E      */ () => incReg(E),
  /* 1D DEC E      */ () => decReg(E),
  /* 1E LD E,n     */ () => regs[E] = next(),
  /* 1F RRA        */ RRA,

  /* 20 JR NZ,e    */ () => fz ? addPC(1) : JR_e(),
  /* 21 LD HL,nn   */ () => ld16Next(HLXY),
  /* 22 LD (nn),HL */ () => ld16(next16(), HLXY),
  /* 23 INC HL     */ () => incReg16(HLXY),
  /* 24 INC H      */ () => incReg(HXY),
  /* 25 DEC H      */ () => decReg(HXY),
  /* 26 LD H,n     */ () => regs[HXY] = next(),
  /* 27 DAA        */ DAA,
  /* 28 JR Z,e     */ () => fz ? JR_e() : addPC(1),
  /* 29 ADD HL,HL  */ () => addHLXY(HLXY),
  /* 2A LD HL,(nn) */ () => ldReg16(HLXY, next16()),
  /* 2B DEC HL     */ () => decReg16(HLXY),
  /* 2C INC L      */ () => incReg(LXY),
  /* 2D DEC L      */ () => decReg(LXY),
  /* 2E LD L,n     */ () => regs[LXY] = next(),
  /* 2F CPL        */ CPL,

  /* 30 JR NC,e    */ () => fc ? addPC(1) : JR_e(),
  /* 31 LD SP,nn   */ () => ld16Next(SP),
  /* 32 LD (nn),A  */ () => set(next16(), regs[A]),
  /* 33 INC SP     */ () => incReg16(SP),
  /* 34 INC (HL)   */ () => inc(getHLXYd()),
  /* 35 DEC (HL)   */ () => dec(getHLXYd()),
  /* 36 LD (HL),n  */ () => set(getHLXYd(), next()),
  /* 37 SCF        */ SCF,
  /* 38 JR C,e     */ () => fc ? JR_e() : addPC(1),
  /* 39 ADD HL,SP  */ () => addHLXY(SP),
  /* 3A LD A,(nn)  */ () => regs[A] = get(next16()),
  /* 3B DEC SP     */ () => decReg16(SP),
  /* 3C INC A      */ () => incReg(A),
  /* 3D DEC A      */ () => decReg(A),
  /* 3E LD A,n     */ () => regs[A] = next(),
  /* 3F CCF        */ CCF,

  /* 40 LD B,B     */ nop,
  /* 41 LD B,C     */ () => regs[B] = regs[C],
  /* 42 LD B,D     */ () => regs[B] = regs[D],
  /* 43 LD B,E     */ () => regs[B] = regs[E],
  /* 44 LD B,H     */ () => regs[B] = regs[HXY],
  /* 45 LD B,L     */ () => regs[B] = regs[LXY],
  /* 46 LD B,(HL)  */ () => regs[B] = get(getHLXYd()),
  /* 47 LD B,A     */ () => regs[B] = regs[A],
  /* 48 LD C,B     */ () => regs[C] = regs[B],
  /* 49 LD C,C     */ nop,
  /* 4A LD C,D     */ () => regs[C] = regs[D],
  /* 4B LD C,E     */ () => regs[C] = regs[E],
  /* 4C LD C,H     */ () => regs[C] = regs[HXY],
  /* 4D LD C,L     */ () => regs[C] = regs[LXY],
  /* 4E LD C,(HL)  */ () => regs[C] = get(getHLXYd()),
  /* 4F LD C,A     */ () => regs[C] = regs[A],

  /* 50 LD D,B     */ () => regs[D] = regs[B],
  /* 51 LD D,C     */ () => regs[D] = regs[C],
  /* 52 LD D,D     */ nop,
  /* 53 LD D,E     */ () => regs[D] = regs[E],
  /* 54 LD D,H     */ () => regs[D] = regs[HXY],
  /* 55 LD D,L     */ () => regs[D] = regs[LXY],
  /* 56 LD D,(HL)  */ () => regs[D] = get(getHLXYd()),
  /* 57 LD D,A     */ () => regs[D] = regs[A],
  /* 58 LD E,B     */ () => regs[E] = regs[B],
  /* 59 LD E,C     */ () => regs[E] = regs[C],
  /* 5A LD E,D     */ () => regs[E] = regs[D],
  /* 5B LD E,E     */ nop,
  /* 5C LD E,H     */ () => regs[E] = regs[HXY],
  /* 5D LD E,L     */ () => regs[E] = regs[LXY],
  /* 5E LD E,(HL)  */ () => regs[E] = get(getHLXYd()),
  /* 5F LD E,A     */ () => regs[E] = regs[A],

  /* 60 LD H,B     */ () => regs[HXY] = regs[B],
  /* 61 LD H,C     */ () => regs[HXY] = regs[C],
  /* 62 LD H,D     */ () => regs[HXY] = regs[D],
  /* 63 LD H,E     */ () => regs[HXY] = regs[E],
  /* 64 LD H,H     */ nop,
  /* 65 LD H,L     */ () => regs[HXY] = regs[LXY],
  /* 66 LD H,(HL)  */ () => regs[H] = get(getHLXYd()),
  /* 67 LD H,A     */ () => regs[HXY] = regs[A],
  /* 68 LD L,B     */ () => regs[LXY] = regs[B],
  /* 69 LD L,C     */ () => regs[LXY] = regs[C],
  /* 6A LD L,D     */ () => regs[LXY] = regs[D],
  /* 6B LD L,E     */ () => regs[LXY] = regs[E],
  /* 6C LD L,H     */ () => regs[LXY] = regs[HXY],
  /* 6D LD L,L     */ nop,
  /* 6E LD L,(HL)  */ () => regs[L] = get(getHLXYd()),
  /* 6F LD L,A     */ () => regs[LXY] = regs[A],

  /* 70 LD (HL),B  */ () => set(getHLXYd(), regs[B]),
  /* 71 LD (HL),C  */ () => set(getHLXYd(), regs[C]),
  /* 72 LD (HL),D  */ () => set(getHLXYd(), regs[D]),
  /* 73 LD (HL),E  */ () => set(getHLXYd(), regs[E]),
  /* 74 LD (HL),H  */ () => set(getHLXYd(), regs[H]),
  /* 75 LD (HL),L  */ () => set(getHLXYd(), regs[L]),
  /* 76 HALT       */ () => { setHLT(HLT); addPC(-1); },
  /* 77 LD (HL),A  */ () => set(getHLXYd(), regs[A]),
  /* 78 LD A,B     */ () => regs[A] = regs[B],
  /* 79 LD A,C     */ () => regs[A] = regs[C],
  /* 7A LD A,D     */ () => regs[A] = regs[D],
  /* 7B LD A,E     */ () => regs[A] = regs[E],
  /* 7C LD A,H     */ () => regs[A] = regs[HXY],
  /* 7D LD A,L     */ () => regs[A] = regs[LXY],
  /* 7E LD A,(HL)  */ () => regs[A] = get(getHLXYd()),
  /* 7F LD A,A     */ nop,

  /* 80 ADD A,B    */ () => add(regs[B]),
  /* 81 ADD A,C    */ () => add(regs[C]),
  /* 82 ADD A,D    */ () => add(regs[D]),
  /* 83 ADD A,E    */ () => add(regs[E]),
  /* 84 ADD A,H    */ () => add(regs[HXY]),
  /* 85 ADD A,L    */ () => add(regs[LXY]),
  /* 86 ADD A,(HL) */ () => add(get(getHLXYd())),
  /* 87 ADD A,A    */ () => add(regs[A]),
  /* 88 ADC A,B    */ () => add(regs[B], fc),
  /* 89 ADC A,C    */ () => add(regs[C], fc),
  /* 8A ADC A,D    */ () => add(regs[D], fc),
  /* 8B ADC A,E    */ () => add(regs[E], fc),
  /* 8C ADC A,H    */ () => add(regs[HXY], fc),
  /* 8D ADC A,L    */ () => add(regs[LXY], fc),
  /* 8E ADC A,(HL) */ () => add(get(getHLXYd()), fc),
  /* 8F ADC A,A    */ () => add(regs[A], fc),

  /* 90 SUB B      */ () => sub(regs[B]),
  /* 91 SUB C      */ () => sub(regs[C]),
  /* 92 SUB D      */ () => sub(regs[D]),
  /* 93 SUB E      */ () => sub(regs[E]),
  /* 94 SUB H      */ () => sub(regs[HXY]),
  /* 95 SUB L      */ () => sub(regs[LXY]),
  /* 96 SUB (HL)   */ () => sub(get(getHLXYd())),
  /* 97 SUB A      */ () => sub(regs[A]),
  /* 98 SBC A,B    */ () => sub(regs[B], fc),
  /* 99 SBC A,C    */ () => sub(regs[C], fc),
  /* 9A SBC A,D    */ () => sub(regs[D], fc),
  /* 9B SBC A,E    */ () => sub(regs[E], fc),
  /* 9C SBC A,H    */ () => sub(regs[HXY], fc),
  /* 9D SBC A,L    */ () => sub(regs[LXY], fc),
  /* 9E SBC A,(HL) */ () => sub(get(getHLXYd()), fc),
  /* 9F SBC A,A    */ () => sub(regs[A], fc),

  /* A0 AND B      */ () => logic(regs[A] & regs[B], FH),
  /* A1 AND C      */ () => logic(regs[A] & regs[C], FH),
  /* A2 AND D      */ () => logic(regs[A] & regs[D], FH),
  /* A3 AND E      */ () => logic(regs[A] & regs[E], FH),
  /* A4 AND H      */ () => logic(regs[A] & regs[HXY], FH),
  /* A5 AND L      */ () => logic(regs[A] & regs[LXY], FH),
  /* A6 AND (HL)   */ () => logic(regs[A] & get(getHLXYd()), FH),
  /* A7 AND A      */ () => logic(regs[A], FH),
  /* A8 XOR B      */ () => logic(regs[A] ^ regs[B]),
  /* A9 XOR C      */ () => logic(regs[A] ^ regs[C]),
  /* AA XOR D      */ () => logic(regs[A] ^ regs[D]),
  /* AB XOR E      */ () => logic(regs[A] ^ regs[E]),
  /* AC XOR H      */ () => logic(regs[A] ^ regs[HXY]),
  /* AD XOR L      */ () => logic(regs[A] ^ regs[LXY]),
  /* AE XOR (HL)   */ () => logic(regs[A] ^ get(getHLXYd())),
  /* AF XOR A      */ () => logic(0),

  /* B0 OR B       */ () => logic(regs[A] | regs[B]),
  /* B1 OR C       */ () => logic(regs[A] | regs[C]),
  /* B2 OR D       */ () => logic(regs[A] | regs[D]),
  /* B3 OR E       */ () => logic(regs[A] | regs[E]),
  /* B4 OR H       */ () => logic(regs[A] | regs[HXY]),
  /* B5 OR L       */ () => logic(regs[A] | regs[LXY]),
  /* B6 OR (HL)    */ () => logic(regs[A] | get(getHLXYd())),
  /* B7 OR A       */ () => logic(regs[A]),
  /* B8 CP B       */ () => cp(regs[B]),
  /* B9 CP C       */ () => cp(regs[C]),
  /* BA CP D       */ () => cp(regs[D]),
  /* BB CP E       */ () => cp(regs[E]),
  /* BC CP H       */ () => cp(regs[HXY]),
  /* BD CP L       */ () => cp(regs[LXY]),
  /* BE CP (HL)    */ () => cp(get(getHLXYd())),
  /* BF CP A       */ () => cp(regs[A]),

  /* C0 RET NZ     */ () => fz ? {} : pop16(PC),
  /* C1 POP BC     */ () => pop16(BC),
  /* C2 JP NZ,nn   */ () => fz ? addPC(2) : setPCNext16(),
  /* C3 JP nn      */ () => setPCNext16(),
  /* C4 CALL NZ,nn */ () => fz ? addPC(2) : callNext16(),
  /* C5 PUSH BC    */ () => push16(BC),
  /* C6 ADD A,n    */ () => add(next()),
  /* C7 CALL 00h   */ () => call88(0x00),
  /* C8 RET Z      */ () => fz ? pop16(PC) : {},
  /* C9 RET        */ () => pop16(PC),
  /* CA JP Z,nn    */ () => fz ? setPCNext16() : addPC(2),
  /* CB -- BIT --- */ () => HLXY === HL ? executeBit() : executeBitXYd(),
  /* CC CALL Z,nn  */ () => fz ? callNext16() : addPC(2),
  /* CD CALL nn    */ () => callNext16(),
  /* CE ADC A,n    */ () => add(next(), fc),
  /* CF CALL 08h   */ () => call88(0x08),

  /* D0 RET NC     */ () => fc ? {} : pop16(PC),
  /* D1 POP DE     */ () => pop16(DE),
  /* D2 JP NC,nn   */ () => fc ? addPC(2) : setPCNext16(),
  /* D3 OUT (n),A  */ OUT_n_A,
  /* D4 CALL NC,nn */ () => fc ? addPC(2) : callNext16(),
  /* D5 PUSH DE    */ () => push16(DE),
  /* D6 SUB A,n    */ () => sub(next()),
  /* D7 CALL 10h   */ () => call88(0x10),
  /* D8 RET C      */ () => fc ? pop16(PC) : {},
  /* D9 EXX        */ EXX,
  /* DA JP C,nn    */ () => fc ? setPCNext16() : addPC(2),
  /* DB IN A,(n)   */ IN_A_n,
  /* DC CALL C,nn  */ () => fc ? callNext16() : addPC(2),
  /* DD --- IX --- */ () => { setHLXY(IX); executeMain(); setHLXY(HL); },
  /* DE SBC A,n    */ () => sub(next(), fc),
  /* DF CALL 18h   */ () => call88(0x18),

  /* E0 RET PO     */ () => fo ? {} : pop16(PC),
  /* E1 POP HL     */ () => pop16(HLXY),
  /* E2 JP PO,nn   */ () => fo ? addPC(2) : setPCNext16(),
  /* E3 EX (SP),HL */ EX_sp_HL,
  /* E4 CALL PO,nn */ () => fo ? addPC(2) : callNext16(),
  /* E5 PUSH HL    */ () => push16(HLXY),
  /* E6 AND n      */ () => logic(regs[A] & next(), FH),
  /* E7 CALL 20h   */ () => call88(0x20),
  /* E8 RET PE     */ () => fo ? pop16(PC) : {},
  /* E9 JP (HL)    */ () => { regs[PCl] = regs[LXY]; regs[PCh] = regs[HXY]; },
  /* EA JP PE,nn   */ () => fo ? setPCNext16() : addPC(2),
  /* EB EX DE,HL   */ EX_DE_HL,
  /* EC CALL PE,nn */ () => fo ? callNext16() : addPC(2),
  /* ED -- MISC -- */ executeMisc,
  /* EE XOR n      */ () => logic(regs[A] ^ next()),
  /* EF CALL 28h   */ () => call88(0x28),

  /* F0 RET P      */ () => fs ? {} : pop16(PC),
  /* F1 POP AF     */ popAF,
  /* F2 JP P,nn    */ () => fs ? addPC(2) : setPCNext16(),
  /* F3 DI         */ () => { setIFF1(0); setIFF2(0); },
  /* F4 CALL P,nn  */ () => fs ? addPC(2) : callNext16(),
  /* F5 PUSH AF    */ pushAF,
  /* F6 OR n       */ () => logic(regs[A] | next()),
  /* F7 RST 30h    */ () => call88(0x30),
  /* F8 RET M      */ () => fs ? pop16(PC) : {},
  /* F9 LD SP,HL   */ () => { regs[SPl] = regs[LXY]; regs[SPh] = regs[HXY]; },
  /* FA JP M,nn    */ () => fs ? setPCNext16() : addPC(2),
  /* FB EI         */ () => { setIFF1(IFF1); setIFF2(IFF2); setEIDelay(1); },
  /* FC CALL M,nn  */ () => fs ? callNext16() : addPC(2),
  /* FD --- IY --- */ () => { setHLXY(IY); executeMain(); setHLXY(HL); },
  /* FE CP n       */ () => cp(next()),
  /* FF CALL 38h   */ () => call88(0x38),
];
