import { get, get16, set } from '../common/utils';
import { executeBit } from './execute-bit';
import { executeBitXYd } from './execute-bit-xyd';
import { executeMisc } from './execute-misc';
import { FH, FO, FS, FZ, HLT, IFF12 } from './flags';
import { call88, callNext16 } from './op/op-call';
import { EX_AF_AF, EX_DE_HL, EX_sp_HL, EXX } from './op/op-exchange';
import { IN_A_n, OUT_n_A } from './op/op-io';
import { DJNZ_e, JR_e } from './op/op-jump';
import { ld16, ld16Next } from './op/op-load-16bit';
import { addHLXY, dec16, inc16 } from './op/op-math-16bit';
import { add, cp, dec, inc, logic, sub } from './op/op-math-8bit';
import { CCF, CPL, DAA, SCF } from './op/op-math-etc';
import { RLA, RLCA, RRA, RRCA } from './op/op-shift';
import { A, AF, B, BC, C, D, DE, E, F, H, HL, HLXY, HXY, IX, IY, L, LXY, PC, PCh, PCl, setHLXY, SP, SPh, SPl, SYS } from './positions';
import { addPC, getFC, getHLXYd, next, next16, nop, pop16, push16, refresh, setEIDelay, setPCNext16 } from './utils';

export function executeMain() {
  refresh();
  if (get(SYS) & HLT) return;
  const op = next();
  opsMain[op]();
}

const opsMain = [
  /* 00 NOP        */ nop,
  /* 01 LD BC,nn   */ () => ld16Next(BC),
  /* 02 LD (BC),A  */ () => set(get16(BC), get(A)),
  /* 03 INC BC     */ () => inc16(BC),
  /* 04 INC B      */ () => inc(B),
  /* 05 DEC B      */ () => dec(B),
  /* 06 LD B,n     */ () => set(B, next()),
  /* 07 RLCA       */ RLCA,
  /* 08 EX AF,AF'  */ EX_AF_AF,
  /* 09 ADD HL,BC  */ () => addHLXY(BC),
  /* 0A LD A,(BC)  */ () => set(A, get(get16(BC))),
  /* 0B DEC BC     */ () => dec16(BC),
  /* 0C INC C      */ () => inc(C),
  /* 0D DEC C      */ () => dec(C),
  /* 0E LD C,n     */ () => set(C, next()),
  /* 0F RRCA       */ RRCA,

  /* 10 DJNZ e     */ DJNZ_e,
  /* 11 LD DE,nn   */ () => ld16Next(DE),
  /* 12 LD (DE),A  */ () => set(get16(DE), get(A)),
  /* 13 INC DE     */ () => inc16(DE),
  /* 14 INC D      */ () => inc(D),
  /* 15 DEC D      */ () => dec(D),
  /* 16 LD D,n     */ () => set(D, next()),
  /* 17 RLA        */ RLA,
  /* 18 JR e       */ JR_e,
  /* 19 ADD HL,DE  */ () => addHLXY(DE),
  /* 1A LD A,(DE)  */ () => set(A, get(get16(DE))),
  /* 1B DEC DE     */ () => dec16(DE),
  /* 1C INC E      */ () => inc(E),
  /* 1D DEC E      */ () => dec(E),
  /* 1E LD E,n     */ () => set(E, next()),
  /* 1F RRA        */ RRA,

  /* 20 JR NZ,e    */ () => get(F) & FZ ? addPC(1) : JR_e(),
  /* 21 LD HL,nn   */ () => ld16Next(HLXY),
  /* 22 LD (nn),HL */ () => ld16(next16(), HLXY),
  /* 23 INC HL     */ () => inc16(HLXY),
  /* 24 INC H      */ () => inc(HXY),
  /* 25 DEC H      */ () => dec(HXY),
  /* 26 LD H,n     */ () => set(HXY, next()),
  /* 27 DAA        */ DAA,
  /* 28 JR Z,e     */ () => get(F) & FZ ? JR_e() : addPC(1),
  /* 29 ADD HL,HL  */ () => addHLXY(HLXY),
  /* 2A LD HL,(nn) */ () => ld16(HLXY, next16()),
  /* 2B DEC HL     */ () => dec16(HLXY),
  /* 2C INC L      */ () => inc(LXY),
  /* 2D DEC L      */ () => dec(LXY),
  /* 2E LD L,n     */ () => set(LXY, next()),
  /* 2F CPL        */ CPL,

  /* 30 JR NC,e    */ () => getFC() ? addPC(1) : JR_e(),
  /* 31 LD SP,nn   */ () => ld16Next(SP),
  /* 32 LD (nn),A  */ () => set(next16(), get(A)),
  /* 33 INC SP     */ () => inc16(SP),
  /* 34 INC (HL)   */ () => inc(getHLXYd()),
  /* 35 DEC (HL)   */ () => dec(getHLXYd()),
  /* 36 LD (HL),n  */ () => set(getHLXYd(), next()),
  /* 37 SCF        */ SCF,
  /* 38 JR C,e     */ () => getFC() ? JR_e() : addPC(1),
  /* 39 ADD HL,SP  */ () => addHLXY(SP),
  /* 3A LD A,(nn)  */ () => set(A, get(next16())),
  /* 3B DEC SP     */ () => dec16(SP),
  /* 3C INC A      */ () => inc(A),
  /* 3D DEC A      */ () => dec(A),
  /* 3E LD A,n     */ () => set(A, next()),
  /* 3F CCF        */ CCF,

  /* 40 LD B,B     */ nop,
  /* 41 LD B,C     */ () => set(B, get(C)),
  /* 42 LD B,D     */ () => set(B, get(D)),
  /* 43 LD B,E     */ () => set(B, get(E)),
  /* 44 LD B,H     */ () => set(B, get(HXY)),
  /* 45 LD B,L     */ () => set(B, get(LXY)),
  /* 46 LD B,(HL)  */ () => set(B, get(getHLXYd())),
  /* 47 LD B,A     */ () => set(B, get(A)),
  /* 48 LD C,B     */ () => set(C, get(B)),
  /* 49 LD C,C     */ nop,
  /* 4A LD C,D     */ () => set(C, get(D)),
  /* 4B LD C,E     */ () => set(C, get(E)),
  /* 4C LD C,H     */ () => set(C, get(HXY)),
  /* 4D LD C,L     */ () => set(C, get(LXY)),
  /* 4E LD C,(HL)  */ () => set(C, get(getHLXYd())),
  /* 4F LD C,A     */ () => set(C, get(A)),

  /* 50 LD D,B     */ () => set(D, get(B)),
  /* 51 LD D,C     */ () => set(D, get(C)),
  /* 52 LD D,D     */ nop,
  /* 53 LD D,E     */ () => set(D, get(E)),
  /* 54 LD D,H     */ () => set(D, get(HXY)),
  /* 55 LD D,L     */ () => set(D, get(LXY)),
  /* 56 LD D,(HL)  */ () => set(D, get(getHLXYd())),
  /* 57 LD D,A     */ () => set(D, get(A)),
  /* 58 LD E,B     */ () => set(E, get(B)),
  /* 59 LD E,C     */ () => set(E, get(C)),
  /* 5A LD E,D     */ () => set(E, get(D)),
  /* 5B LD E,E     */ nop,
  /* 5C LD E,H     */ () => set(E, get(HXY)),
  /* 5D LD E,L     */ () => set(E, get(LXY)),
  /* 5E LD E,(HL)  */ () => set(E, get(getHLXYd())),
  /* 5F LD E,A     */ () => set(E, get(A)),

  /* 60 LD H,B     */ () => set(HXY, get(B)),
  /* 61 LD H,C     */ () => set(HXY, get(C)),
  /* 62 LD H,D     */ () => set(HXY, get(D)),
  /* 63 LD H,E     */ () => set(HXY, get(E)),
  /* 64 LD H,H     */ nop,
  /* 65 LD H,L     */ () => set(HXY, get(LXY)),
  /* 66 LD H,(HL)  */ () => set(H, get(getHLXYd())),
  /* 67 LD H,A     */ () => set(HXY, get(A)),
  /* 68 LD L,B     */ () => set(LXY, get(B)),
  /* 69 LD L,C     */ () => set(LXY, get(C)),
  /* 6A LD L,D     */ () => set(LXY, get(D)),
  /* 6B LD L,E     */ () => set(LXY, get(E)),
  /* 6C LD L,H     */ () => set(LXY, get(HXY)),
  /* 6D LD L,L     */ nop,
  /* 6E LD L,(HL)  */ () => set(L, get(getHLXYd())),
  /* 6F LD L,A     */ () => set(LXY, get(A)),

  /* 70 LD (HL),B  */ () => set(getHLXYd(), get(B)),
  /* 71 LD (HL),C  */ () => set(getHLXYd(), get(C)),
  /* 72 LD (HL),D  */ () => set(getHLXYd(), get(D)),
  /* 73 LD (HL),E  */ () => set(getHLXYd(), get(E)),
  /* 74 LD (HL),H  */ () => set(getHLXYd(), get(H)),
  /* 75 LD (HL),L  */ () => set(getHLXYd(), get(L)),
  /* 76 HALT       */ () => { set(SYS, get(SYS) | HLT); addPC(-1); },
  /* 77 LD (HL),A  */ () => set(getHLXYd(), get(A)),
  /* 78 LD A,B     */ () => set(A, get(B)),
  /* 79 LD A,C     */ () => set(A, get(C)),
  /* 7A LD A,D     */ () => set(A, get(D)),
  /* 7B LD A,E     */ () => set(A, get(E)),
  /* 7C LD A,H     */ () => set(A, get(HXY)),
  /* 7D LD A,L     */ () => set(A, get(LXY)),
  /* 7E LD A,(HL)  */ () => set(A, get(getHLXYd())),
  /* 7F LD A,A     */ nop,

  /* 80 ADD A,B    */ () => add(get(B)),
  /* 81 ADD A,C    */ () => add(get(C)),
  /* 82 ADD A,D    */ () => add(get(D)),
  /* 83 ADD A,E    */ () => add(get(E)),
  /* 84 ADD A,H    */ () => add(get(HXY)),
  /* 85 ADD A,L    */ () => add(get(LXY)),
  /* 86 ADD A,(HL) */ () => add(get(getHLXYd())),
  /* 87 ADD A,A    */ () => add(get(A)),
  /* 88 ADC A,B    */ () => add(get(B), getFC()),
  /* 89 ADC A,C    */ () => add(get(C), getFC()),
  /* 8A ADC A,D    */ () => add(get(D), getFC()),
  /* 8B ADC A,E    */ () => add(get(E), getFC()),
  /* 8C ADC A,H    */ () => add(get(HXY), getFC()),
  /* 8D ADC A,L    */ () => add(get(LXY), getFC()),
  /* 8E ADC A,(HL) */ () => add(get(getHLXYd()), getFC()),
  /* 8F ADC A,A    */ () => add(get(A), getFC()),

  /* 90 SUB B      */ () => sub(get(B)),
  /* 91 SUB C      */ () => sub(get(C)),
  /* 92 SUB D      */ () => sub(get(D)),
  /* 93 SUB E      */ () => sub(get(E)),
  /* 94 SUB H      */ () => sub(get(HXY)),
  /* 95 SUB L      */ () => sub(get(LXY)),
  /* 96 SUB (HL)   */ () => sub(get(getHLXYd())),
  /* 97 SUB A      */ () => sub(get(A)),
  /* 98 SBC A,B    */ () => sub(get(B), getFC()),
  /* 99 SBC A,C    */ () => sub(get(C), getFC()),
  /* 9A SBC A,D    */ () => sub(get(D), getFC()),
  /* 9B SBC A,E    */ () => sub(get(E), getFC()),
  /* 9C SBC A,H    */ () => sub(get(HXY), getFC()),
  /* 9D SBC A,L    */ () => sub(get(LXY), getFC()),
  /* 9E SBC A,(HL) */ () => sub(get(getHLXYd()), getFC()),
  /* 9F SBC A,A    */ () => sub(get(A), getFC()),

  /* A0 AND B      */ () => logic(get(A) & get(B), FH),
  /* A1 AND C      */ () => logic(get(A) & get(C), FH),
  /* A2 AND D      */ () => logic(get(A) & get(D), FH),
  /* A3 AND E      */ () => logic(get(A) & get(E), FH),
  /* A4 AND H      */ () => logic(get(A) & get(HXY), FH),
  /* A5 AND L      */ () => logic(get(A) & get(LXY), FH),
  /* A6 AND (HL)   */ () => logic(get(A) & get(getHLXYd()), FH),
  /* A7 AND A      */ () => logic(get(A), FH),
  /* A8 XOR B      */ () => logic(get(A) ^ get(B)),
  /* A9 XOR C      */ () => logic(get(A) ^ get(C)),
  /* AA XOR D      */ () => logic(get(A) ^ get(D)),
  /* AB XOR E      */ () => logic(get(A) ^ get(E)),
  /* AC XOR H      */ () => logic(get(A) ^ get(HXY)),
  /* AD XOR L      */ () => logic(get(A) ^ get(LXY)),
  /* AE XOR (HL)   */ () => logic(get(A) ^ get(getHLXYd())),
  /* AF XOR A      */ () => logic(0),

  /* B0 OR B       */ () => logic(get(A) | get(B)),
  /* B1 OR C       */ () => logic(get(A) | get(C)),
  /* B2 OR D       */ () => logic(get(A) | get(D)),
  /* B3 OR E       */ () => logic(get(A) | get(E)),
  /* B4 OR H       */ () => logic(get(A) | get(HXY)),
  /* B5 OR L       */ () => logic(get(A) | get(LXY)),
  /* B6 OR (HL)    */ () => logic(get(A) | get(getHLXYd())),
  /* B7 OR A       */ () => logic(get(A)),
  /* B8 CP B       */ () => cp(get(B)),
  /* B9 CP C       */ () => cp(get(C)),
  /* BA CP D       */ () => cp(get(D)),
  /* BB CP E       */ () => cp(get(E)),
  /* BC CP H       */ () => cp(get(HXY)),
  /* BD CP L       */ () => cp(get(LXY)),
  /* BE CP (HL)    */ () => cp(get(getHLXYd())),
  /* BF CP A       */ () => cp(get(A)),

  /* C0 RET NZ     */ () => get(F) & FZ ? {} : pop16(PC),
  /* C1 POP BC     */ () => pop16(BC),
  /* C2 JP NZ,nn   */ () => get(F) & FZ ? addPC(2) : setPCNext16(),
  /* C3 JP nn      */ () => setPCNext16(),
  /* C4 CALL NZ,nn */ () => get(F) & FZ ? addPC(2) : callNext16(),
  /* C5 PUSH BC    */ () => push16(BC),
  /* C6 ADD A,n    */ () => add(next()),
  /* C7 CALL 00h   */ () => call88(0x00),
  /* C8 RET Z      */ () => get(F) & FZ ? pop16(PC) : {},
  /* C9 RET        */ () => pop16(PC),
  /* CA JP Z,nn    */ () => get(F) & FZ ? setPCNext16() : addPC(2),
  /* CB -- BIT --- */ () => HLXY === HL ? executeBit() : executeBitXYd(),
  /* CC CALL Z,nn  */ () => get(F) & FZ ? callNext16() : addPC(2),
  /* CD CALL nn    */ () => callNext16(),
  /* CE ADC A,n    */ () => add(next(), getFC()),
  /* CF CALL 08h   */ () => call88(0x08),

  /* D0 RET NC     */ () => getFC() ? {} : pop16(PC),
  /* D1 POP DE     */ () => pop16(DE),
  /* D2 JP NC,nn   */ () => getFC() ? addPC(2) : setPCNext16(),
  /* D3 OUT (n),A  */ OUT_n_A,
  /* D4 CALL NC,nn */ () => getFC() ? addPC(2) : callNext16(),
  /* D5 PUSH DE    */ () => push16(DE),
  /* D6 SUB A,n    */ () => sub(next()),
  /* D7 CALL 10h   */ () => call88(0x10),
  /* D8 RET C      */ () => getFC() ? pop16(PC) : {},
  /* D9 EXX        */ EXX,
  /* DA JP C,nn    */ () => getFC() ? setPCNext16() : addPC(2),
  /* DB IN A,(n)   */ IN_A_n,
  /* DC CALL C,nn  */ () => getFC() ? callNext16() : addPC(2),
  /* DD --- IX --- */ () => { setHLXY(IX); executeMain(); setHLXY(HL); },
  /* DE SBC A,n    */ () => sub(next(), getFC()),
  /* DF CALL 18h   */ () => call88(0x18),

  /* E0 RET PO     */ () => get(F) & FO ? {} : pop16(PC),
  /* E1 POP HL     */ () => pop16(HLXY),
  /* E2 JP PO,nn   */ () => get(F) & FO ? addPC(2) : setPCNext16(),
  /* E3 EX (SP),HL */ EX_sp_HL,
  /* E4 CALL PO,nn */ () => get(F) & FO ? addPC(2) : callNext16(),
  /* E5 PUSH HL    */ () => push16(HLXY),
  /* E6 AND n      */ () => logic(get(A) & next(), FH),
  /* E7 CALL 20h   */ () => call88(0x20),
  /* E8 RET PE     */ () => get(F) & FO ? pop16(PC) : {},
  /* E9 JP (HL)    */ () => { set(PCl, get(LXY)); set(PCh, get(HXY)); },
  /* EA JP PE,nn   */ () => get(F) & FO ? setPCNext16() : addPC(2),
  /* EB EX DE,HL   */ EX_DE_HL,
  /* EC CALL PE,nn */ () => get(F) & FO ? callNext16() : addPC(2),
  /* ED -- MISC -- */ executeMisc,
  /* EE XOR n      */ () => logic(get(A) ^ next()),
  /* EF CALL 28h   */ () => call88(0x28),

  /* F0 RET P      */ () => get(F) & FS ? {} : pop16(PC),
  /* F1 POP AF     */ () => pop16(AF),
  /* F2 JP P,nn    */ () => get(F) & FS ? addPC(2) : setPCNext16(),
  /* F3 DI         */ () => set(SYS, get(SYS) & ~IFF12),
  /* F4 CALL P,nn  */ () => get(F) & FS ? addPC(2) : callNext16(),
  /* F5 PUSH AF    */ () => push16(AF),
  /* F6 OR n       */ () => logic(get(A) | next()),
  /* F7 RST 30h    */ () => call88(0x30),
  /* F8 RET M      */ () => get(F) & FS ? pop16(PC) : {},
  /* F9 LD SP,HL   */ () => { set(SPl, get(LXY)); set(SPh, get(HXY)); },
  /* FA JP M,nn    */ () => get(F) & FS ? setPCNext16() : addPC(2),
  /* FB EI         */ () => { set(SYS, get(SYS) | IFF12); setEIDelay(1); },
  /* FC CALL M,nn  */ () => get(F) & FS ? callNext16() : addPC(2),
  /* FD --- IY --- */ () => { setHLXY(IY); executeMain(); setHLXY(HL); },
  /* FE CP n       */ () => cp(next()),
  /* FF CALL 38h   */ () => call88(0x38),
];
