import { xFFFF } from '../hw/constants';
import { mem, write, write16 } from '../hw/mem-state';
import { readPort, writePort } from '../hw/ports';
import { executeBit } from './execute-bit';
import { executeBitXYd } from './execute-bit-xyd';
import { executeMisc } from './execute-misc';
import { fc, FH, fp, fs, fz, getF, HLT, hlt, IFF1, IFF2, setF, setHLT, setIFF1, setIFF2 } from './flags';
import { RLA, RLCA, RRA, RRCA } from './op/op-bit';
import { DJNZ_e, JR_e } from './op/op-etc';
import { EX_AF_AF, EX_DE_HL, EX_sp_HL, EXX } from './op/op-exchange';
import { ADD_HL } from './op/op-math-16bit';
import { ADD_ADC, AND_XOR_OR, CP, DEC_hl, DEC_r, INC_hl, INC_r, SUB_SBC } from './op/op-math-8bit';
import { CCF, CPL, DAA, SCF } from './op/op-math-etc';
import { CALL_nn, RET, RST_p } from './op/op-stack';
import { a, b, c, d, decBC, decDE, decHLXY, e, getBC, getDE, getH, getHXY, getL, getLXY, hlxy, incBC, incDE, incHLXY, incPC_, incSP_, isXYMode, normPC, normSP, pc, refresh, setA, setB, setC, setD, setE, setEIDelay, setH, setHXY, setIXMode, setIYMode, setL, setLXY, setPC, setSP, sp, unsetIXMode, unsetIYMode } from './registers';
import { getHLXYd, next, next16, nop, setPCNext16 } from './utils';

export function executeMain() {
  refresh();
  if (hlt) return;
  const op = /*!inline*/ next();
  opsMain[op]();
}

const opsMain = [
  /* 00 NOP        */ nop,
  /* 01 LD BC,nn   */ () => { setC(mem[incPC_()]); setB(mem[incPC_()]); normPC(); },
  /* 02 LD (BC),A  */ () => write(getBC(), a),
  /* 03 INC BC     */ () => incBC(),
  /* 04 INC B      */ () => setB(INC_r(b)),
  /* 05 DEC B      */ () => setB(DEC_r(b)),
  /* 06 LD B,n     */ () => setB(next()),
  /* 07 RLCA       */ RLCA,
  /* 08 EX AF,AF'  */ EX_AF_AF,
  /* 09 ADD HL,BC  */ () => ADD_HL(getBC()),
  /* 0A LD A,(BC)  */ () => setA(mem[getBC()]),
  /* 0B DEC BC     */ () => decBC(),
  /* 0C INC C      */ () => setC(INC_r(c)),
  /* 0D DEC C      */ () => setC(DEC_r(c)),
  /* 0E LD C,n     */ () => setC(next()),
  /* 0F RRCA       */ RRCA,

  /* 10 DJNZ e     */ DJNZ_e,
  /* 11 LD DE,nn   */ () => { setE(mem[incPC_()]); setD(mem[incPC_()]); normPC(); },
  /* 12 LD (DE),A  */ () => write(getDE(), a),
  /* 13 INC DE     */ () => incDE(),
  /* 14 INC D      */ () => setD(INC_r(d)),
  /* 15 DEC D      */ () => setD(DEC_r(d)),
  /* 16 LD D,n     */ () => setD(next()),
  /* 17 RLA        */ RLA,
  /* 18 JR e       */ JR_e,
  /* 19 ADD HL,DE  */ () => ADD_HL(getDE()),
  /* 1A LD A,(DE)  */ () => setA(mem[getDE()]),
  /* 1B DEC DE     */ () => decDE(),
  /* 1C INC E      */ () => setE(INC_r(e)),
  /* 1D DEC E      */ () => setE(DEC_r(e)),
  /* 1E LD E,n     */ () => setE(next()),
  /* 1F RRA        */ RRA,

  /* 20 JR NZ,e    */ () => fz ? setPC((pc + 1) & xFFFF) : JR_e(),
  /* 21 LD HL,nn   */ () => { setLXY(mem[incPC_()]); setHXY(mem[incPC_()]); normPC(); },
  /* 22 LD (nn),HL */ () => write16(next16(), getLXY(), getHXY()),
  /* 23 INC HL     */ () => incHLXY(),
  /* 24 INC H      */ () => setHXY(INC_r(getHXY())),
  /* 25 DEC H      */ () => setHXY(DEC_r(getHXY())),
  /* 26 LD H,n     */ () => setHXY(next()),
  /* 27 DAA        */ DAA,
  /* 28 JR Z,e     */ () => fz ? JR_e() : setPC((pc + 1) & xFFFF),
  /* 29 ADD HL,HL  */ () => ADD_HL(hlxy),
  /* 2A LD HL,(nn) */ () => { const nn = next16(); setLXY(mem[nn]); setHXY(mem[nn + 1]); },
  /* 2B DEC HL     */ () => decHLXY(),
  /* 2C INC L      */ () => setLXY(INC_r(getLXY())),
  /* 2D DEC L      */ () => setLXY(DEC_r(getLXY())),
  /* 2E LD L,n     */ () => setLXY(next()),
  /* 2F CPL        */ CPL,

  /* 30 JR NC,e    */ () => fc ? setPC((pc + 1) & xFFFF) : JR_e(),
  /* 31 LD SP,nn   */ () => { setSP(mem[incPC_()] | (mem[incPC_()] << 8)); normPC(); },
  /* 32 LD (nn),A  */ () => write(next16(), a),
  /* 33 INC SP     */ () => setSP((sp + 1) & xFFFF),
  /* 34 INC (HL)   */ INC_hl,
  /* 35 DEC (HL)   */ DEC_hl,
  /* 36 LD (HL),n  */ () => write(getHLXYd(), next()),
  /* 37 SCF        */ SCF,
  /* 38 JR C,e     */ () => fc ? JR_e() : setPC((pc + 1) & xFFFF),
  /* 39 ADD HL,SP  */ () => ADD_HL(sp),
  /* 3A LD A,(nn)  */ () => setA(mem[next16()]),
  /* 3B DEC SP     */ () => setSP((sp - 1) & xFFFF),
  /* 3C INC A      */ () => setA(INC_r(a)),
  /* 3D DEC A      */ () => setA(DEC_r(a)),
  /* 3E LD A,n     */ () => setA(next()),
  /* 3F CCF        */ CCF,

  /* 40 LD B,B     */ nop,
  /* 41 LD B,C     */ () => setB(c),
  /* 42 LD B,D     */ () => setB(d),
  /* 43 LD B,E     */ () => setB(e),
  /* 44 LD B,H     */ () => setB(getHXY()),
  /* 45 LD B,L     */ () => setB(getLXY()),
  /* 46 LD B,(HL)  */ () => setB(mem[getHLXYd()]),
  /* 47 LD B,A     */ () => setB(a),
  /* 48 LD C,B     */ () => setC(b),
  /* 49 LD C,C     */ nop,
  /* 4A LD C,D     */ () => setC(d),
  /* 4B LD C,E     */ () => setC(e),
  /* 4C LD C,H     */ () => setC(getHXY()),
  /* 4D LD C,L     */ () => setC(getLXY()),
  /* 4E LD C,(HL)  */ () => setC(mem[getHLXYd()]),
  /* 4F LD C,A     */ () => setC(a),

  /* 50 LD D,B     */ () => setD(b),
  /* 51 LD D,C     */ () => setD(c),
  /* 52 LD D,D     */ nop,
  /* 53 LD D,E     */ () => setD(e),
  /* 54 LD D,H     */ () => setD(getHXY()),
  /* 55 LD D,L     */ () => setD(getLXY()),
  /* 56 LD D,(HL)  */ () => setD(mem[getHLXYd()]),
  /* 57 LD D,A     */ () => setD(a),
  /* 58 LD E,B     */ () => setE(b),
  /* 59 LD E,C     */ () => setE(c),
  /* 5A LD E,D     */ () => setE(d),
  /* 5B LD E,E     */ nop,
  /* 5C LD E,H     */ () => setE(getHXY()),
  /* 5D LD E,L     */ () => setE(getLXY()),
  /* 5E LD E,(HL)  */ () => setE(mem[getHLXYd()]),
  /* 5F LD E,A     */ () => setE(a),

  /* 60 LD H,B     */ () => setHXY(b),
  /* 61 LD H,C     */ () => setHXY(c),
  /* 62 LD H,D     */ () => setHXY(d),
  /* 63 LD H,E     */ () => setHXY(e),
  /* 64 LD H,H     */ nop,
  /* 65 LD H,L     */ () => setHXY(getLXY()),
  /* 66 LD H,(HL)  */ () => setH(mem[getHLXYd()]),
  /* 67 LD H,A     */ () => setHXY(a),
  /* 68 LD L,B     */ () => setLXY(b),
  /* 69 LD L,C     */ () => setLXY(c),
  /* 6A LD L,D     */ () => setLXY(d),
  /* 6B LD L,E     */ () => setLXY(e),
  /* 6C LD L,H     */ () => setLXY(getHXY()),
  /* 6D LD L,L     */ nop,
  /* 6E LD L,(HL)  */ () => setL(mem[getHLXYd()]),
  /* 6F LD L,A     */ () => setLXY(a),

  /* 70 LD (HL),B  */ () => write(getHLXYd(), b),
  /* 71 LD (HL),C  */ () => write(getHLXYd(), c),
  /* 72 LD (HL),D  */ () => write(getHLXYd(), d),
  /* 73 LD (HL),E  */ () => write(getHLXYd(), e),
  /* 74 LD (HL),H  */ () => write(getHLXYd(), getH()),
  /* 75 LD (HL),L  */ () => write(getHLXYd(), getL()),
  /* 76 HALT       */ () => { setHLT(HLT); setPC((pc - 1) & xFFFF); },
  /* 77 LD (HL),A  */ () => write(getHLXYd(), a),
  /* 78 LD A,B     */ () => setA(b),
  /* 79 LD A,C     */ () => setA(c),
  /* 7A LD A,D     */ () => setA(d),
  /* 7B LD A,E     */ () => setA(e),
  /* 7C LD A,H     */ () => setA(getHXY()),
  /* 7D LD A,L     */ () => setA(getLXY()),
  /* 7E LD A,(HL)  */ () => setA(mem[getHLXYd()]),
  /* 7F LD A,A     */ nop,

  /* 80 ADD A,B    */ () => ADD_ADC(b),
  /* 81 ADD A,C    */ () => ADD_ADC(c),
  /* 82 ADD A,D    */ () => ADD_ADC(d),
  /* 83 ADD A,E    */ () => ADD_ADC(e),
  /* 84 ADD A,H    */ () => ADD_ADC(getHXY()),
  /* 85 ADD A,L    */ () => ADD_ADC(getLXY()),
  /* 86 ADD A,(HL) */ () => ADD_ADC(mem[getHLXYd()]),
  /* 87 ADD A,A    */ () => ADD_ADC(a),
  /* 88 ADC A,B    */ () => ADD_ADC(b, fc),
  /* 89 ADC A,C    */ () => ADD_ADC(c, fc),
  /* 8A ADC A,D    */ () => ADD_ADC(d, fc),
  /* 8B ADC A,E    */ () => ADD_ADC(e, fc),
  /* 8C ADC A,H    */ () => ADD_ADC(getHXY(), fc),
  /* 8D ADC A,L    */ () => ADD_ADC(getLXY(), fc),
  /* 8E ADC A,(HL) */ () => ADD_ADC(mem[getHLXYd()], fc),
  /* 8F ADC A,A    */ () => ADD_ADC(a, fc),

  /* 90 SUB B      */ () => SUB_SBC(b),
  /* 91 SUB C      */ () => SUB_SBC(c),
  /* 92 SUB D      */ () => SUB_SBC(d),
  /* 93 SUB E      */ () => SUB_SBC(e),
  /* 94 SUB H      */ () => SUB_SBC(getHXY()),
  /* 95 SUB L      */ () => SUB_SBC(getLXY()),
  /* 96 SUB (HL)   */ () => SUB_SBC(mem[getHLXYd()]),
  /* 97 SUB A      */ () => SUB_SBC(a),
  /* 98 SBC A,B    */ () => SUB_SBC(b, fc),
  /* 99 SBC A,C    */ () => SUB_SBC(c, fc),
  /* 9A SBC A,D    */ () => SUB_SBC(d, fc),
  /* 9B SBC A,E    */ () => SUB_SBC(e, fc),
  /* 9C SBC A,H    */ () => SUB_SBC(getHXY(), fc),
  /* 9D SBC A,L    */ () => SUB_SBC(getLXY(), fc),
  /* 9E SBC A,(HL) */ () => SUB_SBC(mem[getHLXYd()], fc),
  /* 9F SBC A,A    */ () => SUB_SBC(a, fc),

  /* A0 AND B      */ () => AND_XOR_OR(a & b, FH),
  /* A1 AND C      */ () => AND_XOR_OR(a & c, FH),
  /* A2 AND D      */ () => AND_XOR_OR(a & d, FH),
  /* A3 AND E      */ () => AND_XOR_OR(a & e, FH),
  /* A4 AND H      */ () => AND_XOR_OR(a & getHXY(), FH),
  /* A5 AND L      */ () => AND_XOR_OR(a & getLXY(), FH),
  /* A6 AND (HL)   */ () => AND_XOR_OR(a & mem[getHLXYd()], FH),
  /* A7 AND A      */ () => AND_XOR_OR(a, FH),
  /* A8 XOR B      */ () => AND_XOR_OR(a ^ b),
  /* A9 XOR C      */ () => AND_XOR_OR(a ^ c),
  /* AA XOR D      */ () => AND_XOR_OR(a ^ d),
  /* AB XOR E      */ () => AND_XOR_OR(a ^ e),
  /* AC XOR H      */ () => AND_XOR_OR(a ^ getHXY()),
  /* AD XOR L      */ () => AND_XOR_OR(a ^ getLXY()),
  /* AE XOR (HL)   */ () => AND_XOR_OR(a ^ mem[getHLXYd()]),
  /* AF XOR A      */ () => AND_XOR_OR(0),

  /* B0 OR B       */ () => AND_XOR_OR(a | b),
  /* B1 OR C       */ () => AND_XOR_OR(a | c),
  /* B2 OR D       */ () => AND_XOR_OR(a | d),
  /* B3 OR E       */ () => AND_XOR_OR(a | e),
  /* B4 OR H       */ () => AND_XOR_OR(a | getHXY()),
  /* B5 OR L       */ () => AND_XOR_OR(a | getLXY()),
  /* B6 OR (HL)    */ () => AND_XOR_OR(a | mem[getHLXYd()]),
  /* B7 OR A       */ () => AND_XOR_OR(a),
  /* B8 CP B       */ () => CP(b),
  /* B9 CP C       */ () => CP(c),
  /* BA CP D       */ () => CP(d),
  /* BB CP E       */ () => CP(e),
  /* BC CP H       */ () => CP(getHXY()),
  /* BD CP L       */ () => CP(getLXY()),
  /* BE CP (HL)    */ () => CP(mem[getHLXYd()]),
  /* BF CP A       */ () => CP(a),

  /* C0 RET NZ     */ () => fz ? {} : RET(),
  /* C1 POP BC     */ () => { setC(mem[incSP_()]); setB(mem[incSP_()]); normSP(); },
  /* C2 JP NZ,nn   */ () => fz ? setPC((pc + 2) & xFFFF) : setPCNext16(),
  /* C3 JP nn      */ () => setPCNext16(),
  /* C4 CALL NZ,nn */ () => fz ? setPC((pc + 2) & xFFFF) : CALL_nn(),
  /* C5 PUSH BC    */ () => { setSP((sp - 2) & xFFFF); write16(sp, c, b); },
  /* C6 ADD A,n    */ () => ADD_ADC(next()),
  /* C7 RST 00h    */ () => RST_p(0x00),
  /* C8 RET Z      */ () => fz ? RET() : {},
  /* C9 RET        */ () => RET(),
  /* CA JP Z,nn    */ () => fz ? setPCNext16() : setPC((pc + 2) & xFFFF),
  /* CB -- BIT --- */ () => isXYMode ? executeBitXYd() : executeBit(),
  /* CC CALL Z,nn  */ () => fz ? CALL_nn() : setPC((pc + 2) & xFFFF),
  /* CD CALL nn    */ () => CALL_nn(),
  /* CE ADC A,n    */ () => ADD_ADC(next(), fc),
  /* CF RST 08h    */ () => RST_p(0x08),

  /* D0 RET NC     */ () => fc ? {} : RET(),
  /* D1 POP DE     */ () => { setE(mem[incSP_()]); setD(mem[incSP_()]); normSP(); },
  /* D2 JP NC,nn   */ () => fc ? setPC((pc + 2) & xFFFF) : setPCNext16(),
  /* D3 OUT (n),A  */ () => writePort(next(), a, a),
  /* D4 CALL NC,nn */ () => fc ? setPC((pc + 2) & xFFFF) : CALL_nn(),
  /* D5 PUSH DE    */ () => { setSP((sp - 2) & xFFFF); write16(sp, e, d); },
  /* D6 SUB A,n    */ () => SUB_SBC(next()),
  /* D7 RST 10h    */ () => RST_p(0x10),
  /* D8 RET C      */ () => fc ? RET() : {},
  /* D9 EXX        */ EXX,
  /* DA JP C,nn    */ () => fc ? setPCNext16() : setPC((pc + 2) & xFFFF),
  /* DB IN A,(n)   */ () => setA(readPort(next(), a)),
  /* DC CALL C,nn  */ () => fc ? CALL_nn() : setPC((pc + 2) & xFFFF),
  /* DD --- IX --- */ () => { setIXMode(); executeMain(); unsetIXMode(); },
  /* DE SBC A,n    */ () => SUB_SBC(next(), fc),
  /* DF RST 18h    */ () => RST_p(0x18),

  /* E0 RET PO     */ () => fp ? {} : RET(),
  /* E1 POP HL     */ () => { setLXY(mem[incSP_()]); setHXY(mem[incSP_()]); normSP(); },
  /* E2 JP PO,nn   */ () => fp ? setPC((pc + 2) & xFFFF) : setPCNext16(),
  /* E3 EX (SP),HL */ EX_sp_HL,
  /* E4 CALL PO,nn */ () => fp ? setPC((pc + 2) & xFFFF) : CALL_nn(),
  /* E5 PUSH HL    */ () => { setSP((sp - 2) & xFFFF); write16(sp, getLXY(), getHXY()); },
  /* E6 AND n      */ () => AND_XOR_OR(a & next(), FH),
  /* E7 RST 20h    */ () => RST_p(0x20),
  /* E8 RET PE     */ () => fp ? RET() : {},
  /* E9 JP (HL)    */ () => { setPC(getLXY() | (getHXY() << 8)); },
  /* EA JP PE,nn   */ () => fp ? setPCNext16() : setPC((pc + 2) & xFFFF),
  /* EB EX DE,HL   */ EX_DE_HL,
  /* EC CALL PE,nn */ () => fp ? CALL_nn() : setPC((pc + 2) & xFFFF),
  /* ED -- MISC -- */ executeMisc,
  /* EE XOR n      */ () => AND_XOR_OR(a ^ next()),
  /* EF RST 28h    */ () => RST_p(0x28),

  /* F0 RET P      */ () => fs ? {} : RET(),
  /* F1 POP AF     */ () => { setF(mem[incSP_()]); setA(mem[incSP_()]); normSP(); },
  /* F2 JP P,nn    */ () => fs ? setPC((pc + 2) & xFFFF) : setPCNext16(),
  /* F3 DI         */ () => { setIFF1(0); setIFF2(0); },
  /* F4 CALL P,nn  */ () => fs ? setPC((pc + 2) & xFFFF) : CALL_nn(),
  /* F5 PUSH AF    */ () => { setSP((sp - 2) & xFFFF); write16(sp, getF(), a); },
  /* F6 OR n       */ () => AND_XOR_OR(a | next()),
  /* F7 RST 30h    */ () => RST_p(0x30),
  /* F8 RET M      */ () => fs ? RET() : {},
  /* F9 LD SP,HL   */ () => { setSP(getLXY() | (getHXY() << 8)); },
  /* FA JP M,nn    */ () => fs ? setPCNext16() : setPC((pc + 2) & xFFFF),
  /* FB EI         */ () => { setIFF1(IFF1); setIFF2(IFF2); setEIDelay(1); },
  /* FC CALL M,nn  */ () => fs ? CALL_nn() : setPC((pc + 2) & xFFFF),
  /* FD --- IY --- */ () => { setIYMode(); executeMain(); unsetIYMode(); },
  /* FE CP n       */ () => CP(next()),
  /* FF RST 38h    */ () => RST_p(0x38),
];
