import { BIT0, BIT1, BIT2, BIT3, BIT4, BIT5, BIT6, BIT7 } from '../hw/constants';
import { mem, write } from '../hw/memory';
import { BIT_b_r, RL_val, RLC_val, RR_val, RRC_val, SLA_val, SLL_val, SRA_val, SRL_val } from './op/op-bit';
import { setA, setB, setC, setD, setE, setH, setL } from './registers';
import { getHLXYd, next } from './utils';

let xydAddr = 0;
let xydVal = 0;

/** IX Bit Instructions (DDCB) | IY Bit Instructions (FDCB) */
export function executeBitXYd() {
  xydAddr = getHLXYd();
  xydVal = mem[xydAddr];
  opsBitXY[next()]();
}

function testBitXYd(bit: number) {
  BIT_b_r(xydVal & bit, xydAddr >> 8);
}

function setXYd_undoc(value: number): number {
  write(xydAddr, value);
  return value;
}

const opsBitXY: (() => void)[] = [
  /* 00 RLC (XY+d),B   * */ () => setB(setXYd_undoc(RLC_val(xydVal))),
  /* 01 RLC (XY+d),C   * */ () => setC(setXYd_undoc(RLC_val(xydVal))),
  /* 02 RLC (XY+d),D   * */ () => setD(setXYd_undoc(RLC_val(xydVal))),
  /* 03 RLC (XY+d),E   * */ () => setE(setXYd_undoc(RLC_val(xydVal))),
  /* 04 RLC (XY+d),H   * */ () => setH(setXYd_undoc(RLC_val(xydVal))),
  /* 05 RLC (XY+d),L   * */ () => setL(setXYd_undoc(RLC_val(xydVal))),
  /* 06 RLC (XY+d)       */ () => write(xydAddr, RLC_val(xydVal)),
  /* 07 RLC (XY+d),A   * */ () => setA(setXYd_undoc(RLC_val(xydVal))),
  /* 08 RRC (XY+d),B   * */ () => setB(setXYd_undoc(RRC_val(xydVal))),
  /* 09 RRC (XY+d),C   * */ () => setC(setXYd_undoc(RRC_val(xydVal))),
  /* 0A RRC (XY+d),D   * */ () => setD(setXYd_undoc(RRC_val(xydVal))),
  /* 0B RRC (XY+d),E   * */ () => setE(setXYd_undoc(RRC_val(xydVal))),
  /* 0C RRC (XY+d),H   * */ () => setH(setXYd_undoc(RRC_val(xydVal))),
  /* 0D RRC (XY+d),L   * */ () => setL(setXYd_undoc(RRC_val(xydVal))),
  /* 0E RRC (XY+d)       */ () => write(xydAddr, RRC_val(xydVal)),
  /* 0F RRC (XY+d),A   * */ () => setA(setXYd_undoc(RRC_val(xydVal))),

  /* 10 RL (XY+d),B    * */ () => setB(setXYd_undoc(RL_val(xydVal))),
  /* 11 RL (XY+d),C    * */ () => setC(setXYd_undoc(RL_val(xydVal))),
  /* 12 RL (XY+d),D    * */ () => setD(setXYd_undoc(RL_val(xydVal))),
  /* 13 RL (XY+d),E    * */ () => setE(setXYd_undoc(RL_val(xydVal))),
  /* 14 RL (XY+d),H    * */ () => setH(setXYd_undoc(RL_val(xydVal))),
  /* 15 RL (XY+d),L    * */ () => setL(setXYd_undoc(RL_val(xydVal))),
  /* 16 RL (XY+d)        */ () => write(xydAddr, RL_val(xydVal)),
  /* 17 RL (XY+d),A    * */ () => setA(setXYd_undoc(RL_val(xydVal))),
  /* 18 RR (XY+d),B    * */ () => setB(setXYd_undoc(RR_val(xydVal))),
  /* 19 RR (XY+d),C    * */ () => setC(setXYd_undoc(RR_val(xydVal))),
  /* 1A RR (XY+d),D    * */ () => setD(setXYd_undoc(RR_val(xydVal))),
  /* 1B RR (XY+d),E    * */ () => setE(setXYd_undoc(RR_val(xydVal))),
  /* 1C RR (XY+d),H    * */ () => setH(setXYd_undoc(RR_val(xydVal))),
  /* 1D RR (XY+d),L    * */ () => setL(setXYd_undoc(RR_val(xydVal))),
  /* 1E RR (XY+d)        */ () => write(xydAddr, RR_val(xydVal)),
  /* 1F RR (XY+d),A    * */ () => setA(setXYd_undoc(RR_val(xydVal))),

  /* 20 SLA (XY+d),B   * */ () => setB(setXYd_undoc(SLA_val(xydVal))),
  /* 21 SLA (XY+d),C   * */ () => setC(setXYd_undoc(SLA_val(xydVal))),
  /* 22 SLA (XY+d),D   * */ () => setD(setXYd_undoc(SLA_val(xydVal))),
  /* 23 SLA (XY+d),E   * */ () => setE(setXYd_undoc(SLA_val(xydVal))),
  /* 24 SLA (XY+d),H   * */ () => setH(setXYd_undoc(SLA_val(xydVal))),
  /* 25 SLA (XY+d),L   * */ () => setL(setXYd_undoc(SLA_val(xydVal))),
  /* 26 SLA (XY+d)       */ () => write(xydAddr, SLA_val(xydVal)),
  /* 27 SLA (XY+d),A   * */ () => setA(setXYd_undoc(SLA_val(xydVal))),
  /* 28 SRA (XY+d),B   * */ () => setB(setXYd_undoc(SRA_val(xydVal))),
  /* 29 SRA (XY+d),C   * */ () => setC(setXYd_undoc(SRA_val(xydVal))),
  /* 2A SRA (XY+d),D   * */ () => setD(setXYd_undoc(SRA_val(xydVal))),
  /* 2B SRA (XY+d),E   * */ () => setE(setXYd_undoc(SRA_val(xydVal))),
  /* 2C SRA (XY+d),H   * */ () => setH(setXYd_undoc(SRA_val(xydVal))),
  /* 2D SRA (XY+d),L   * */ () => setL(setXYd_undoc(SRA_val(xydVal))),
  /* 2E SRA (XY+d)       */ () => write(xydAddr, SRA_val(xydVal)),
  /* 2F SRA (XY+d),A   * */ () => setA(setXYd_undoc(SRA_val(xydVal))),

  /* 30 SLL (XY+d),B   * */ () => setB(setXYd_undoc(SLL_val(xydVal))),
  /* 31 SLL (XY+d),C   * */ () => setC(setXYd_undoc(SLL_val(xydVal))),
  /* 32 SLL (XY+d),D   * */ () => setD(setXYd_undoc(SLL_val(xydVal))),
  /* 33 SLL (XY+d),E   * */ () => setE(setXYd_undoc(SLL_val(xydVal))),
  /* 34 SLL (XY+d),H   * */ () => setH(setXYd_undoc(SLL_val(xydVal))),
  /* 35 SLL (XY+d),L   * */ () => setL(setXYd_undoc(SLL_val(xydVal))),
  /* 36 SLL (XY+d)     * */ () => write(xydAddr, SLL_val(xydVal)),
  /* 37 SLL (XY+d),A   * */ () => setA(setXYd_undoc(SLL_val(xydVal))),
  /* 38 SRL (XY+d),B   * */ () => setB(setXYd_undoc(SRL_val(xydVal))),
  /* 39 SRL (XY+d),C   * */ () => setC(setXYd_undoc(SRL_val(xydVal))),
  /* 3A SRL (XY+d),D   * */ () => setD(setXYd_undoc(SRL_val(xydVal))),
  /* 3B SRL (XY+d),E   * */ () => setE(setXYd_undoc(SRL_val(xydVal))),
  /* 3C SRL (XY+d),H   * */ () => setH(setXYd_undoc(SRL_val(xydVal))),
  /* 3D SRL (XY+d),L   * */ () => setL(setXYd_undoc(SRL_val(xydVal))),
  /* 3E SRL (XY+d)       */ () => write(xydAddr, SRL_val(xydVal)),
  /* 3F SRL (XY+d),A   * */ () => setA(setXYd_undoc(SRL_val(xydVal))),

  /* 40 BIT 0,(XY+d)   * */ () => testBitXYd(BIT0),
  /* 41 BIT 0,(XY+d)   * */ () => testBitXYd(BIT0),
  /* 42 BIT 0,(XY+d)   * */ () => testBitXYd(BIT0),
  /* 43 BIT 0,(XY+d)   * */ () => testBitXYd(BIT0),
  /* 44 BIT 0,(XY+d)   * */ () => testBitXYd(BIT0),
  /* 45 BIT 0,(XY+d)   * */ () => testBitXYd(BIT0),
  /* 46 BIT 0,(XY+d)     */ () => testBitXYd(BIT0),
  /* 47 BIT 0,(XY+d)   * */ () => testBitXYd(BIT0),
  /* 48 BIT 1,(XY+d)   * */ () => testBitXYd(BIT1),
  /* 49 BIT 1,(XY+d)   * */ () => testBitXYd(BIT1),
  /* 4A BIT 1,(XY+d)   * */ () => testBitXYd(BIT1),
  /* 4B BIT 1,(XY+d)   * */ () => testBitXYd(BIT1),
  /* 4C BIT 1,(XY+d)   * */ () => testBitXYd(BIT1),
  /* 4D BIT 1,(XY+d)   * */ () => testBitXYd(BIT1),
  /* 4E BIT 1,(XY+d)     */ () => testBitXYd(BIT1),
  /* 4F BIT 1,(XY+d)   * */ () => testBitXYd(BIT1),

  /* 50 BIT 2,(XY+d)   * */ () => testBitXYd(BIT2),
  /* 51 BIT 2,(XY+d)   * */ () => testBitXYd(BIT2),
  /* 52 BIT 2,(XY+d)   * */ () => testBitXYd(BIT2),
  /* 53 BIT 2,(XY+d)   * */ () => testBitXYd(BIT2),
  /* 54 BIT 2,(XY+d)   * */ () => testBitXYd(BIT2),
  /* 55 BIT 2,(XY+d)   * */ () => testBitXYd(BIT2),
  /* 56 BIT 2,(XY+d)     */ () => testBitXYd(BIT2),
  /* 57 BIT 2,(XY+d)   * */ () => testBitXYd(BIT2),
  /* 58 BIT 3,(XY+d)   * */ () => testBitXYd(BIT3),
  /* 59 BIT 3,(XY+d)   * */ () => testBitXYd(BIT3),
  /* 5A BIT 3,(XY+d)   * */ () => testBitXYd(BIT3),
  /* 5B BIT 3,(XY+d)   * */ () => testBitXYd(BIT3),
  /* 5C BIT 3,(XY+d)   * */ () => testBitXYd(BIT3),
  /* 5D BIT 3,(XY+d)   * */ () => testBitXYd(BIT3),
  /* 5E BIT 3,(XY+d)     */ () => testBitXYd(BIT3),
  /* 5F BIT 3,(XY+d)   * */ () => testBitXYd(BIT3),

  /* 60 BIT 4,(XY+d)   * */ () => testBitXYd(BIT4),
  /* 61 BIT 4,(XY+d)   * */ () => testBitXYd(BIT4),
  /* 62 BIT 4,(XY+d)   * */ () => testBitXYd(BIT4),
  /* 63 BIT 4,(XY+d)   * */ () => testBitXYd(BIT4),
  /* 64 BIT 4,(XY+d)   * */ () => testBitXYd(BIT4),
  /* 65 BIT 4,(XY+d)   * */ () => testBitXYd(BIT4),
  /* 66 BIT 4,(XY+d)     */ () => testBitXYd(BIT4),
  /* 67 BIT 4,(XY+d)   * */ () => testBitXYd(BIT4),
  /* 68 BIT 5,(XY+d)   * */ () => testBitXYd(BIT5),
  /* 69 BIT 5,(XY+d)   * */ () => testBitXYd(BIT5),
  /* 6A BIT 5,(XY+d)   * */ () => testBitXYd(BIT5),
  /* 6B BIT 5,(XY+d)   * */ () => testBitXYd(BIT5),
  /* 6C BIT 5,(XY+d)   * */ () => testBitXYd(BIT5),
  /* 6D BIT 5,(XY+d)   * */ () => testBitXYd(BIT5),
  /* 6E BIT 5,(XY+d)     */ () => testBitXYd(BIT5),
  /* 6F BIT 5,(XY+d)   * */ () => testBitXYd(BIT5),

  /* 70 BIT 6,(XY+d)   * */ () => testBitXYd(BIT6),
  /* 71 BIT 6,(XY+d)   * */ () => testBitXYd(BIT6),
  /* 72 BIT 6,(XY+d)   * */ () => testBitXYd(BIT6),
  /* 73 BIT 6,(XY+d)   * */ () => testBitXYd(BIT6),
  /* 74 BIT 6,(XY+d)   * */ () => testBitXYd(BIT6),
  /* 75 BIT 6,(XY+d)     */ () => testBitXYd(BIT6),
  /* 76 BIT 6,(XY+d)   * */ () => testBitXYd(BIT6),
  /* 77 BIT 6,(XY+d)   * */ () => testBitXYd(BIT6),
  /* 78 BIT 7,(XY+d)   * */ () => testBitXYd(BIT7),
  /* 79 BIT 7,(XY+d)   * */ () => testBitXYd(BIT7),
  /* 7A BIT 7,(XY+d)   * */ () => testBitXYd(BIT7),
  /* 7B BIT 7,(XY+d)   * */ () => testBitXYd(BIT7),
  /* 7C BIT 7,(XY+d)   * */ () => testBitXYd(BIT7),
  /* 7D BIT 7,(XY+d)   * */ () => testBitXYd(BIT7),
  /* 7E BIT 7,(XY+d)     */ () => testBitXYd(BIT7),
  /* 7F BIT 7,(XY+d)   * */ () => testBitXYd(BIT7),

  /* 80 RES 0,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT0)),
  /* 81 RES 0,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT0)),
  /* 82 RES 0,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT0)),
  /* 83 RES 0,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT0)),
  /* 84 RES 0,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT0)),
  /* 85 RES 0,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT0)),
  /* 86 RES 0,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT0),
  /* 87 RES 0,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT0)),
  /* 88 RES 1,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT1)),
  /* 89 RES 1,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT1)),
  /* 8A RES 1,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT1)),
  /* 8B RES 1,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT1)),
  /* 8C RES 1,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT1)),
  /* 8D RES 1,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT1)),
  /* 8E RES 1,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT1),
  /* 8F RES 1,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT1)),

  /* 90 RES 2,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT2)),
  /* 91 RES 2,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT2)),
  /* 92 RES 2,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT2)),
  /* 93 RES 2,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT2)),
  /* 94 RES 2,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT2)),
  /* 95 RES 2,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT2)),
  /* 96 RES 2,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT2),
  /* 97 RES 2,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT2)),
  /* 98 RES 3,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT3)),
  /* 99 RES 3,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT3)),
  /* 9A RES 3,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT3)),
  /* 9B RES 3,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT3)),
  /* 9C RES 3,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT3)),
  /* 9D RES 3,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT3)),
  /* 9E RES 3,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT3),
  /* 9F RES 3,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT3)),

  /* A0 RES 4,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT4)),
  /* A1 RES 4,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT4)),
  /* A2 RES 4,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT4)),
  /* A3 RES 4,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT4)),
  /* A4 RES 4,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT4)),
  /* A5 RES 4,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT4)),
  /* A6 RES 4,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT4),
  /* A7 RES 4,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT4)),
  /* A8 RES 5,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT5)),
  /* A9 RES 5,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT5)),
  /* AA RES 5,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT5)),
  /* AB RES 5,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT5)),
  /* AC RES 5,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT5)),
  /* AD RES 5,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT5)),
  /* AE RES 5,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT5),
  /* AF RES 5,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT5)),

  /* B0 RES 6,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT6)),
  /* B1 RES 6,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT6)),
  /* B2 RES 6,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT6)),
  /* B3 RES 6,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT6)),
  /* B4 RES 6,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT6)),
  /* B5 RES 6,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT6)),
  /* B6 RES 6,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT6),
  /* B7 RES 6,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT6)),
  /* B8 RES 7,(XY+d),B * */ () => setB(setXYd_undoc(xydVal & ~BIT7)),
  /* B9 RES 7,(XY+d),C * */ () => setC(setXYd_undoc(xydVal & ~BIT7)),
  /* BA RES 7,(XY+d),D * */ () => setD(setXYd_undoc(xydVal & ~BIT7)),
  /* BB RES 7,(XY+d),E * */ () => setE(setXYd_undoc(xydVal & ~BIT7)),
  /* BC RES 7,(XY+d),H * */ () => setH(setXYd_undoc(xydVal & ~BIT7)),
  /* BD RES 7,(XY+d),L * */ () => setL(setXYd_undoc(xydVal & ~BIT7)),
  /* BE RES 7,(XY+d)     */ () => write(xydAddr, xydVal & ~BIT7),
  /* BF RES 7,(XY+d),A * */ () => setA(setXYd_undoc(xydVal & ~BIT7)),

  /* C0 SET 0,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT0)),
  /* C1 SET 0,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT0)),
  /* C2 SET 0,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT0)),
  /* C3 SET 0,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT0)),
  /* C4 SET 0,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT0)),
  /* C5 SET 0,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT0)),
  /* C6 SET 0,(XY+d)     */ () => write(xydAddr, xydVal | BIT0),
  /* C7 SET 0,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT0)),
  /* C8 SET 1,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT1)),
  /* C9 SET 1,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT1)),
  /* CA SET 1,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT1)),
  /* CB SET 1,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT1)),
  /* CC SET 1,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT1)),
  /* CD SET 1,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT1)),
  /* CE SET 1,(XY+d)     */ () => write(xydAddr, xydVal | BIT1),
  /* CF SET 1,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT1)),

  /* D0 SET 2,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT2)),
  /* D1 SET 2,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT2)),
  /* D2 SET 2,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT2)),
  /* D3 SET 2,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT2)),
  /* D4 SET 2,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT2)),
  /* D5 SET 2,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT2)),
  /* D6 SET 2,(XY+d)     */ () => write(xydAddr, xydVal | BIT2),
  /* D7 SET 2,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT2)),
  /* D8 SET 3,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT3)),
  /* D9 SET 3,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT3)),
  /* DA SET 3,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT3)),
  /* DB SET 3,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT3)),
  /* DC SET 3,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT3)),
  /* DD SET 3,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT3)),
  /* DE SET 3,(XY+d)     */ () => write(xydAddr, xydVal | BIT3),
  /* DF SET 3,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT3)),

  /* E0 SET 4,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT4)),
  /* E1 SET 4,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT4)),
  /* E2 SET 4,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT4)),
  /* E3 SET 4,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT4)),
  /* E4 SET 4,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT4)),
  /* E5 SET 4,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT4)),
  /* E6 SET 4,(XY+d)     */ () => write(xydAddr, xydVal | BIT4),
  /* E7 SET 4,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT4)),
  /* E8 SET 5,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT5)),
  /* E9 SET 5,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT5)),
  /* EA SET 5,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT5)),
  /* EB SET 5,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT5)),
  /* EC SET 5,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT5)),
  /* ED SET 5,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT5)),
  /* EE SET 5,(XY+d)     */ () => write(xydAddr, xydVal | BIT5),
  /* EF SET 5,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT5)),

  /* F0 SET 6,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT6)),
  /* F1 SET 6,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT6)),
  /* F2 SET 6,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT6)),
  /* F3 SET 6,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT6)),
  /* F4 SET 6,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT6)),
  /* F5 SET 6,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT6)),
  /* F6 SET 6,(XY+d)     */ () => write(xydAddr, xydVal | BIT6),
  /* F7 SET 6,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT6)),
  /* F8 SET 7,(XY+d),B * */ () => setB(setXYd_undoc(xydVal | BIT7)),
  /* F9 SET 7,(XY+d),C * */ () => setC(setXYd_undoc(xydVal | BIT7)),
  /* FA SET 7,(XY+d),D * */ () => setD(setXYd_undoc(xydVal | BIT7)),
  /* FB SET 7,(XY+d),E * */ () => setE(setXYd_undoc(xydVal | BIT7)),
  /* FC SET 7,(XY+d),H * */ () => setH(setXYd_undoc(xydVal | BIT7)),
  /* FD SET 7,(XY+d),L * */ () => setL(setXYd_undoc(xydVal | BIT7)),
  /* FE SET 7,(XY+d)     */ () => write(xydAddr, xydVal | BIT7),
  /* FF SET 7,(XY+d),A * */ () => setA(setXYd_undoc(xydVal | BIT7)),
];
