import { BIT0, BIT1, BIT2, BIT3, BIT4, BIT5, BIT6, BIT7 } from '../common/constants';
import { mem, write } from '../common/memory';
import { BIT_b_r, RL_val, RLC_val, RR_val, RRC_val, SLA_val, SLL_val, SRA_val, SRL_val } from './op/op-bit';
import { a, b, c, d, e, getHXY, getLXY, hlxy, refresh, setA, setB, setC, setD, setE, setHXY, setLXY, wzh } from './registers';
import { next, ts } from './utils';

/** Bit Instructions (CB) */
export function executeBit() {
  refresh();
  const op = next();
  ts(tstatesBit[op]);
  opsBit[op]();
}

function testBitVal(bit: number, value: number) {
  BIT_b_r(value & bit, value);
}

function testBit(bit: number) {
  BIT_b_r(mem[hlxy] & bit, wzh);
}

function resBitMem(bit: number, addr: number) {
  write(addr, mem[addr] & bit);
}

function setBitMem(bit: number, addr: number) {
  write(addr, mem[addr] | bit);
}

const opsBit: (() => void)[] = [
  /* 00 RLC B      */ () => setB(RLC_val(b)),
  /* 01 RLC C      */ () => setC(RLC_val(c)),
  /* 02 RLC D      */ () => setD(RLC_val(d)),
  /* 03 RLC E      */ () => setE(RLC_val(e)),
  /* 04 RLC H      */ () => setHXY(RLC_val(getHXY())),
  /* 05 RLC L      */ () => setLXY(RLC_val(getLXY())),
  /* 06 RLC (HL)   */ () => write(hlxy, RLC_val(mem[hlxy])),
  /* 07 RLC A      */ () => setA(RLC_val(a)),
  /* 08 RRC B      */ () => setB(RRC_val(b)),
  /* 09 RRC C      */ () => setC(RRC_val(c)),
  /* 0A RRC D      */ () => setD(RRC_val(d)),
  /* 0B RRC E      */ () => setE(RRC_val(e)),
  /* 0C RRC H      */ () => setHXY(RRC_val(getHXY())),
  /* 0D RRC L      */ () => setLXY(RRC_val(getLXY())),
  /* 0E RRC (HL)   */ () => write(hlxy, RRC_val(mem[hlxy])),
  /* 0F RRC A      */ () => setA(RRC_val(a)),

  /* 10 RL B       */ () => setB(RL_val(b)),
  /* 11 RL C       */ () => setC(RL_val(c)),
  /* 12 RL D       */ () => setD(RL_val(d)),
  /* 13 RL E       */ () => setE(RL_val(e)),
  /* 14 RL H       */ () => setHXY(RL_val(getHXY())),
  /* 15 RL L       */ () => setLXY(RL_val(getLXY())),
  /* 16 RL (HL)    */ () => write(hlxy, RL_val(mem[hlxy])),
  /* 17 RL A       */ () => setA(RL_val(a)),
  /* 18 RR B       */ () => setB(RR_val(b)),
  /* 19 RR C       */ () => setC(RR_val(c)),
  /* 1A RR D       */ () => setD(RR_val(d)),
  /* 1B RR E       */ () => setE(RR_val(e)),
  /* 1C RR H       */ () => setHXY(RR_val(getHXY())),
  /* 1D RR L       */ () => setLXY(RR_val(getLXY())),
  /* 1E RR (HL)    */ () => write(hlxy, RR_val(mem[hlxy])),
  /* 1F RR A       */ () => setA(RR_val(a)),

  /* 20 SLA B      */ () => setB(SLA_val(b)),
  /* 21 SLA C      */ () => setC(SLA_val(c)),
  /* 22 SLA D      */ () => setD(SLA_val(d)),
  /* 23 SLA E      */ () => setE(SLA_val(e)),
  /* 24 SLA H      */ () => setHXY(SLA_val(getHXY())),
  /* 25 SLA L      */ () => setLXY(SLA_val(getLXY())),
  /* 26 SLA (HL)   */ () => write(hlxy, SLA_val(mem[hlxy])),
  /* 27 SLA A      */ () => setA(SLA_val(a)),
  /* 28 SRA B      */ () => setB(SRA_val(b)),
  /* 29 SRA C      */ () => setC(SRA_val(c)),
  /* 2A SRA D      */ () => setD(SRA_val(d)),
  /* 2B SRA E      */ () => setE(SRA_val(e)),
  /* 2C SRA H      */ () => setHXY(SRA_val(getHXY())),
  /* 2D SRA L      */ () => setLXY(SRA_val(getLXY())),
  /* 2E SRA (HL)   */ () => write(hlxy, SRA_val(mem[hlxy])),
  /* 2F SRA A      */ () => setA(SRA_val(a)),

  /* 30 SLL B    * */ () => setB(SLL_val(b)),
  /* 31 SLL C    * */ () => setC(SLL_val(c)),
  /* 32 SLL D    * */ () => setD(SLL_val(d)),
  /* 33 SLL E    * */ () => setE(SLL_val(e)),
  /* 34 SLL H    * */ () => setHXY(SLL_val(getHXY())),
  /* 35 SLL L    * */ () => setLXY(SLL_val(getLXY())),
  /* 36 SLL (HL) * */ () => write(hlxy, SLL_val(mem[hlxy])),
  /* 37 SLL A    * */ () => setA(SLL_val(a)),
  /* 38 SRL B      */ () => setB(SRL_val(b)),
  /* 39 SRL C      */ () => setC(SRL_val(c)),
  /* 3A SRL D      */ () => setD(SRL_val(d)),
  /* 3B SRL E      */ () => setE(SRL_val(e)),
  /* 3C SRL H      */ () => setHXY(SRL_val(getHXY())),
  /* 3D SRL L      */ () => setLXY(SRL_val(getLXY())),
  /* 3E SRL (HL)   */ () => write(hlxy, SRL_val(mem[hlxy])),
  /* 3F SRL A      */ () => setA(SRL_val(a)),

  /* 40 BIT 0,B    */ () => testBitVal(BIT0, b),
  /* 41 BIT 0,C    */ () => testBitVal(BIT0, c),
  /* 42 BIT 0,D    */ () => testBitVal(BIT0, d),
  /* 43 BIT 0,E    */ () => testBitVal(BIT0, e),
  /* 44 BIT 0,H    */ () => testBitVal(BIT0, getHXY()),
  /* 45 BIT 0,L    */ () => testBitVal(BIT0, getLXY()),
  /* 46 BIT 0,(HL) */ () => testBit(BIT0),
  /* 47 BIT 0,A    */ () => testBitVal(BIT0, a),
  /* 48 BIT 1,B    */ () => testBitVal(BIT1, b),
  /* 49 BIT 1,C    */ () => testBitVal(BIT1, c),
  /* 4A BIT 1,D    */ () => testBitVal(BIT1, d),
  /* 4B BIT 1,E    */ () => testBitVal(BIT1, e),
  /* 4C BIT 1,H    */ () => testBitVal(BIT1, getHXY()),
  /* 4D BIT 1,L    */ () => testBitVal(BIT1, getLXY()),
  /* 4E BIT 1,(HL) */ () => testBit(BIT1),
  /* 4F BIT 1,A    */ () => testBitVal(BIT1, a),

  /* 50 BIT 2,B    */ () => testBitVal(BIT2, b),
  /* 51 BIT 2,C    */ () => testBitVal(BIT2, c),
  /* 52 BIT 2,D    */ () => testBitVal(BIT2, d),
  /* 53 BIT 2,E    */ () => testBitVal(BIT2, e),
  /* 54 BIT 2,H    */ () => testBitVal(BIT2, getHXY()),
  /* 55 BIT 2,L    */ () => testBitVal(BIT2, getLXY()),
  /* 56 BIT 2,(HL) */ () => testBit(BIT2),
  /* 57 BIT 2,A    */ () => testBitVal(BIT2, a),
  /* 58 BIT 3,B    */ () => testBitVal(BIT3, b),
  /* 59 BIT 3,C    */ () => testBitVal(BIT3, c),
  /* 5A BIT 3,D    */ () => testBitVal(BIT3, d),
  /* 5B BIT 3,E    */ () => testBitVal(BIT3, e),
  /* 5C BIT 3,H    */ () => testBitVal(BIT3, getHXY()),
  /* 5D BIT 3,L    */ () => testBitVal(BIT3, getLXY()),
  /* 5E BIT 3,(HL) */ () => testBit(BIT3),
  /* 5F BIT 3,A    */ () => testBitVal(BIT3, a),

  /* 60 BIT 4,B    */ () => testBitVal(BIT4, b),
  /* 61 BIT 4,C    */ () => testBitVal(BIT4, c),
  /* 62 BIT 4,D    */ () => testBitVal(BIT4, d),
  /* 63 BIT 4,E    */ () => testBitVal(BIT4, e),
  /* 64 BIT 4,H    */ () => testBitVal(BIT4, getHXY()),
  /* 65 BIT 4,L    */ () => testBitVal(BIT4, getLXY()),
  /* 66 BIT 4,(HL) */ () => testBit(BIT4),
  /* 67 BIT 4,A    */ () => testBitVal(BIT4, a),
  /* 68 BIT 5,B    */ () => testBitVal(BIT5, b),
  /* 69 BIT 5,C    */ () => testBitVal(BIT5, c),
  /* 6A BIT 5,D    */ () => testBitVal(BIT5, d),
  /* 6B BIT 5,E    */ () => testBitVal(BIT5, e),
  /* 6C BIT 5,H    */ () => testBitVal(BIT5, getHXY()),
  /* 6D BIT 5,L    */ () => testBitVal(BIT5, getLXY()),
  /* 6E BIT 5,(HL) */ () => testBit(BIT5),
  /* 6F BIT 5,A    */ () => testBitVal(BIT5, a),

  /* 70 BIT 6,B    */ () => testBitVal(BIT6, b),
  /* 71 BIT 6,C    */ () => testBitVal(BIT6, c),
  /* 72 BIT 6,D    */ () => testBitVal(BIT6, d),
  /* 73 BIT 6,E    */ () => testBitVal(BIT6, e),
  /* 74 BIT 6,H    */ () => testBitVal(BIT6, getHXY()),
  /* 75 BIT 6,L    */ () => testBitVal(BIT6, getLXY()),
  /* 76 BIT 6,(HL) */ () => testBit(BIT6),
  /* 77 BIT 6,A    */ () => testBitVal(BIT6, a),
  /* 78 BIT 7,B    */ () => testBitVal(BIT7, b),
  /* 79 BIT 7,C    */ () => testBitVal(BIT7, c),
  /* 7A BIT 7,D    */ () => testBitVal(BIT7, d),
  /* 7B BIT 7,E    */ () => testBitVal(BIT7, e),
  /* 7C BIT 7,H    */ () => testBitVal(BIT7, getHXY()),
  /* 7D BIT 7,L    */ () => testBitVal(BIT7, getLXY()),
  /* 7E BIT 7,(HL) */ () => testBit(BIT7),
  /* 7F BIT 7,A    */ () => testBitVal(BIT7, a),

  /* 80 RES 0,B    */ () => setB(b & ~BIT0),
  /* 81 RES 0,C    */ () => setC(c & ~BIT0),
  /* 82 RES 0,D    */ () => setD(d & ~BIT0),
  /* 83 RES 0,E    */ () => setE(e & ~BIT0),
  /* 84 RES 0,H    */ () => setHXY(getHXY() & ~BIT0),
  /* 85 RES 0,L    */ () => setLXY(getLXY() & ~BIT0),
  /* 86 RES 0,(HL) */ () => resBitMem(~BIT0, hlxy),
  /* 87 RES 0,A    */ () => setA(a & ~BIT0),
  /* 88 RES 1,B    */ () => setB(b & ~BIT1),
  /* 89 RES 1,C    */ () => setC(c & ~BIT1),
  /* 8A RES 1,D    */ () => setD(d & ~BIT1),
  /* 8B RES 1,E    */ () => setE(e & ~BIT1),
  /* 8C RES 1,H    */ () => setHXY(getHXY() & ~BIT1),
  /* 8D RES 1,L    */ () => setLXY(getLXY() & ~BIT1),
  /* 8E RES 1,(HL) */ () => resBitMem(~BIT1, hlxy),
  /* 8F RES 1,A    */ () => setA(a & ~BIT1),

  /* 90 RES 2,B    */ () => setB(b & ~BIT2),
  /* 91 RES 2,C    */ () => setC(c & ~BIT2),
  /* 92 RES 2,D    */ () => setD(d & ~BIT2),
  /* 93 RES 2,E    */ () => setE(e & ~BIT2),
  /* 94 RES 2,H    */ () => setHXY(getHXY() & ~BIT2),
  /* 95 RES 2,L    */ () => setLXY(getLXY() & ~BIT2),
  /* 96 RES 2,(HL) */ () => resBitMem(~BIT2, hlxy),
  /* 97 RES 2,A    */ () => setA(a & ~BIT2),
  /* 98 RES 3,B    */ () => setB(b & ~BIT3),
  /* 99 RES 3,C    */ () => setC(c & ~BIT3),
  /* 9A RES 3,D    */ () => setD(d & ~BIT3),
  /* 9B RES 3,E    */ () => setE(e & ~BIT3),
  /* 9C RES 3,H    */ () => setHXY(getHXY() & ~BIT3),
  /* 9D RES 3,L    */ () => setLXY(getLXY() & ~BIT3),
  /* 9E RES 3,(HL) */ () => resBitMem(~BIT3, hlxy),
  /* 9F RES 3,A    */ () => setA(a & ~BIT3),

  /* A0 RES 4,B    */ () => setB(b & ~BIT4),
  /* A1 RES 4,C    */ () => setC(c & ~BIT4),
  /* A2 RES 4,D    */ () => setD(d & ~BIT4),
  /* A3 RES 4,E    */ () => setE(e & ~BIT4),
  /* A4 RES 4,H    */ () => setHXY(getHXY() & ~BIT4),
  /* A5 RES 4,L    */ () => setLXY(getLXY() & ~BIT4),
  /* A6 RES 4,(HL) */ () => resBitMem(~BIT4, hlxy),
  /* A7 RES 4,A    */ () => setA(a & ~BIT4),
  /* A8 RES 5,B    */ () => setB(b & ~BIT5),
  /* A9 RES 5,C    */ () => setC(c & ~BIT5),
  /* AA RES 5,D    */ () => setD(d & ~BIT5),
  /* AB RES 5,E    */ () => setE(e & ~BIT5),
  /* AC RES 5,H    */ () => setHXY(getHXY() & ~BIT5),
  /* AD RES 5,L    */ () => setLXY(getLXY() & ~BIT5),
  /* AE RES 5,(HL) */ () => resBitMem(~BIT5, hlxy),
  /* AF RES 5,A    */ () => setA(a & ~BIT5),

  /* B0 RES 6,B    */ () => setB(b & ~BIT6),
  /* B1 RES 6,C    */ () => setC(c & ~BIT6),
  /* B2 RES 6,D    */ () => setD(d & ~BIT6),
  /* B3 RES 6,E    */ () => setE(e & ~BIT6),
  /* B4 RES 6,H    */ () => setHXY(getHXY() & ~BIT6),
  /* B5 RES 6,L    */ () => setLXY(getLXY() & ~BIT6),
  /* B6 RES 6,(HL) */ () => resBitMem(~BIT6, hlxy),
  /* B7 RES 6,A    */ () => setA(a & ~BIT6),
  /* B8 RES 7,B    */ () => setB(b & ~BIT7),
  /* B9 RES 7,C    */ () => setC(c & ~BIT7),
  /* BA RES 7,D    */ () => setD(d & ~BIT7),
  /* BB RES 7,E    */ () => setE(e & ~BIT7),
  /* BC RES 7,H    */ () => setHXY(getHXY() & ~BIT7),
  /* BD RES 7,L    */ () => setLXY(getLXY() & ~BIT7),
  /* BE RES 7,(HL) */ () => resBitMem(~BIT7, hlxy),
  /* BF RES 7,A    */ () => setA(a & ~BIT7),

  /* C0 SET 0,B    */ () => setB(b | BIT0),
  /* C1 SET 0,C    */ () => setC(c | BIT0),
  /* C2 SET 0,D    */ () => setD(d | BIT0),
  /* C3 SET 0,E    */ () => setE(e | BIT0),
  /* C4 SET 0,H    */ () => setHXY(getHXY() | BIT0),
  /* C5 SET 0,L    */ () => setLXY(getLXY() | BIT0),
  /* C6 SET 0,(HL) */ () => setBitMem(BIT0, hlxy),
  /* C7 SET 0,A    */ () => setA(a | BIT0),
  /* C8 SET 1,B    */ () => setB(b | BIT1),
  /* C9 SET 1,C    */ () => setC(c | BIT1),
  /* CA SET 1,D    */ () => setD(d | BIT1),
  /* CB SET 1,E    */ () => setE(e | BIT1),
  /* CC SET 1,H    */ () => setHXY(getHXY() | BIT1),
  /* CD SET 1,L    */ () => setLXY(getLXY() | BIT1),
  /* CE SET 1,(HL) */ () => setBitMem(BIT1, hlxy),
  /* CF SET 1,A    */ () => setA(a | BIT1),

  /* D0 SET 2,B    */ () => setB(b | BIT2),
  /* D1 SET 2,C    */ () => setC(c | BIT2),
  /* D2 SET 2,D    */ () => setD(d | BIT2),
  /* D3 SET 2,E    */ () => setE(e | BIT2),
  /* D4 SET 2,H    */ () => setHXY(getHXY() | BIT2),
  /* D5 SET 2,L    */ () => setLXY(getLXY() | BIT2),
  /* D6 SET 2,(HL) */ () => setBitMem(BIT2, hlxy),
  /* D7 SET 2,A    */ () => setA(a | BIT2),
  /* D8 SET 3,B    */ () => setB(b | BIT3),
  /* D9 SET 3,C    */ () => setC(c | BIT3),
  /* DA SET 3,D    */ () => setD(d | BIT3),
  /* DB SET 3,E    */ () => setE(e | BIT3),
  /* DC SET 3,H    */ () => setHXY(getHXY() | BIT3),
  /* DD SET 3,L    */ () => setLXY(getLXY() | BIT3),
  /* DE SET 3,(HL) */ () => setBitMem(BIT3, hlxy),
  /* DF SET 3,A    */ () => setA(a | BIT3),

  /* E0 SET 4,B    */ () => setB(b | BIT4),
  /* E1 SET 4,C    */ () => setC(c | BIT4),
  /* E2 SET 4,D    */ () => setD(d | BIT4),
  /* E3 SET 4,E    */ () => setE(e | BIT4),
  /* E4 SET 4,H    */ () => setHXY(getHXY() | BIT4),
  /* E5 SET 4,L    */ () => setLXY(getLXY() | BIT4),
  /* E6 SET 4,(HL) */ () => setBitMem(BIT4, hlxy),
  /* E7 SET 4,A    */ () => setA(a | BIT4),
  /* E8 SET 5,B    */ () => setB(b | BIT5),
  /* E9 SET 5,C    */ () => setC(c | BIT5),
  /* EA SET 5,D    */ () => setD(d | BIT5),
  /* EB SET 5,E    */ () => setE(e | BIT5),
  /* EC SET 5,H    */ () => setHXY(getHXY() | BIT5),
  /* ED SET 5,L    */ () => setLXY(getLXY() | BIT5),
  /* EE SET 5,(HL) */ () => setBitMem(BIT5, hlxy),
  /* EF SET 5,A    */ () => setA(a | BIT5),

  /* F0 SET 6,B    */ () => setB(b | BIT6),
  /* F1 SET 6,C    */ () => setC(c | BIT6),
  /* F2 SET 6,D    */ () => setD(d | BIT6),
  /* F3 SET 6,E    */ () => setE(e | BIT6),
  /* F4 SET 6,H    */ () => setHXY(getHXY() | BIT6),
  /* F5 SET 6,L    */ () => setLXY(getLXY() | BIT6),
  /* F6 SET 6,(HL) */ () => setBitMem(BIT6, hlxy),
  /* F7 SET 6,A    */ () => setA(a | BIT6),
  /* F8 SET 7,B    */ () => setB(b | BIT7),
  /* F9 SET 7,C    */ () => setC(c | BIT7),
  /* FA SET 7,D    */ () => setD(d | BIT7),
  /* FB SET 7,E    */ () => setE(e | BIT7),
  /* FC SET 7,H    */ () => setHXY(getHXY() | BIT7),
  /* FD SET 7,L    */ () => setLXY(getLXY() | BIT7),
  /* FE SET 7,(HL) */ () => setBitMem(BIT7, hlxy),
  /* FF SET 7,A    */ () => setA(a | BIT7),
];

const tstatesBit = [
  /* 0x */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* 1x */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* 2x */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* 3x */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* 4x */ 8, 8, 8, 8, 8, 8, 12, 8, 8, 8, 8, 8, 8, 8, 12, 8,
  /* 5x */ 8, 8, 8, 8, 8, 8, 12, 8, 8, 8, 8, 8, 8, 8, 12, 8,
  /* 6x */ 8, 8, 8, 8, 8, 8, 12, 8, 8, 8, 8, 8, 8, 8, 12, 8,
  /* 7x */ 8, 8, 8, 8, 8, 8, 12, 8, 8, 8, 8, 8, 8, 8, 12, 8,
  /* 8x */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* 9x */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* Ax */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* Bx */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* Cx */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* Dx */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* Ex */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
  /* Fx */ 8, 8, 8, 8, 8, 8, 15, 8, 8, 8, 8, 8, 8, 8, 15, 8,
];
